package edu.imi.ir.eduimiws.models.wsdl.behdad;

import edu.imi.ir.eduimiws.models.wsdl.attendance.EtsGeneralDataProviderService;
import org.springframework.core.io.ResourceLoader;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-05-26T15:52:25.864+03:30
 * Generated source version: 3.6.5
 *
 */
@WebServiceClient(name = "AccountServiceImplService",
                  wsdlLocation = "https://behdadservices.cbinasim.ir:5050/behdad-account/v2/accountservice?wsdl",
                  targetNamespace = "http://v.service.account.behdad.bis.misc.com/")
public class AccountServiceImplService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://v.service.account.behdad.bis.misc.com/", "AccountServiceImplService");
    public static final QName AccountServiceImplPort = new QName("http://v.service.account.behdad.bis.misc.com/", "AccountServiceImplPort");
    static {
        URL resourceUR = ResourceLoader.class.getClassLoader().getResource("wsdl/behdadAccountServiceNew.xml");
        URL url = null;
        try {
//            url = URI.create("file:/C:/Users/O120F~1.ASH/AppData/Local/Temp/tempdir15005984490174745728.tmp/accountservice_1.wsdl").toURL();
//        } catch (MalformedURLException e) {
//            java.util.logging.Logger.getLogger(AccountServiceImplService.class.getName())
//                .log(java.util.logging.Level.INFO,
//                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/O120F~1.ASH/AppData/Local/Temp/tempdir15005984490174745728.tmp/accountservice_1.wsdl");
//        }
            if (resourceUR != null) {
                url = resourceUR;
            }
        } catch (Exception e) {
            java.util.logging.Logger.getLogger(EtsGeneralDataProviderService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "wsdl/behdadSoapService.xml");
        }
        WSDL_LOCATION = url;
    }

    public AccountServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccountServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AccountServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AccountServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AccountServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AccountService
     */
    @WebEndpoint(name = "AccountServiceImplPort")
    public AccountService getAccountServiceImplPort() {
        return super.getPort(AccountServiceImplPort, AccountService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountService
     */
    @WebEndpoint(name = "AccountServiceImplPort")
    public AccountService getAccountServiceImplPort(WebServiceFeature... features) {
        return super.getPort(AccountServiceImplPort, AccountService.class, features);
    }

}
