package edu.imi.ir.eduimiws.models.wsdl.behdad;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-05-26T15:52:25.851+03:30
 * Generated source version: 3.6.5
 *
 */
@WebService(targetNamespace = "com.misc.bis.behdad.service", name = "AccountService")
@XmlSeeAlso({ObjectFactory.class})
public interface AccountService {

    @WebMethod
    @RequestWrapper(localName = "setAccountControlType", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.SetAccountControlType")
    @ResponseWrapper(localName = "setAccountControlTypeResponse", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.SetAccountControlTypeResponse")
    public void setAccountControlType(

        @WebParam(name = "credential", targetNamespace = "")
        Credential credential,
        @WebParam(name = "createModel", targetNamespace = "")
        AccountControlCreateModel createModel
    ) throws InvalidCredentialException_Exception, UnableToAuthenticateException_Exception, PasswordShouldBeChangeException_Exception, InvalidCertificateException_Exception, UserTemporarilySuspendedException_Exception, UnableToGetClientCertificateInfo_Exception, ExpiredOrNotValidCertificateException_Exception, InvalidIdentifierControlTypeException_Exception, InvalidIdentifierTypeException_Exception, InvalidDateException_Exception, PasswordIsNotStrongException_Exception;

    @WebMethod
    @RequestWrapper(localName = "changePassword", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.ChangePasswordResponse")
    public void changePassword(

        @WebParam(name = "changePasswordRequest", targetNamespace = "")
        ChangePasswordRequest changePasswordRequest
    ) throws InvalidCredentialException_Exception, UnableToAuthenticateException_Exception, PasswordShouldBeChangeException_Exception, UnableToChangePasswordException_Exception, InvalidCertificateException_Exception, UserTemporarilySuspendedException_Exception, ExpiredOrNotValidCertificateException_Exception, UnableToGetClientCertificateInfo_Exception, PasswordIsNotStrongException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAccountBalance", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.GetAccountBalance")
    @ResponseWrapper(localName = "getAccountBalanceResponse", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.GetAccountBalanceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public BalanceInfo getAccountBalance(

        @WebParam(name = "credential", targetNamespace = "")
        Credential credential,
        @WebParam(name = "accountInfo", targetNamespace = "")
        AccountInfo accountInfo
    ) throws InvalidCredentialException_Exception, UnableToAuthenticateException_Exception, PasswordShouldBeChangeException_Exception, InvalidCertificateException_Exception, UserTemporarilySuspendedException_Exception, ExpiredOrNotValidCertificateException_Exception, UnableToGetClientCertificateInfo_Exception, PasswordIsNotStrongException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPagedDestinationSideTransactions", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.GetPagedDestinationSideTransactions")
    @ResponseWrapper(localName = "getPagedDestinationSideTransactionsResponse", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.GetPagedDestinationSideTransactionsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PagedData getPagedDestinationSideTransactions(

        @WebParam(name = "credential", targetNamespace = "")
        Credential credential,
        @WebParam(name = "sideTransactionsRequest", targetNamespace = "")
        SideTransactionsRequest sideTransactionsRequest,
        @WebParam(name = "paging", targetNamespace = "")
        Paging paging
    ) throws InvalidCredentialException_Exception, PasswordShouldBeChangeException_Exception, PageSizeIsTooMuchException_Exception, InvalidPageNumberException_Exception, UnableToAuthenticateException_Exception, InvalidTransactionTypeException_Exception, InvalidPageSizeException_Exception, InvalidCertificateException_Exception, UserTemporarilySuspendedException_Exception, UnableToGetClientCertificateInfo_Exception, ExpiredOrNotValidCertificateException_Exception, TransactionDoesNotBelongToAccount_Exception, PasswordIsNotStrongException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getBankTransactionsDetails", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.GetBankTransactionsDetails")
    @ResponseWrapper(localName = "getBankTransactionsDetailsResponse", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.GetBankTransactionsDetailsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PagedData getBankTransactionsDetails(

        @WebParam(name = "credential", targetNamespace = "")
        Credential credential,
        @WebParam(name = "filter", targetNamespace = "")
        AccountTransactionFilter filter,
        @WebParam(name = "paging", targetNamespace = "")
        Paging paging
    ) throws InvalidCredentialException_Exception, PasswordShouldBeChangeException_Exception, PageSizeIsTooMuchException_Exception, InvalidPageNumberException_Exception, UnableToAuthenticateException_Exception, InvalidPageSizeException_Exception, UnableToGetTransactionsException_Exception, InvalidCertificateException_Exception, UserTemporarilySuspendedException_Exception, UnableToGetClientCertificateInfo_Exception, ExpiredOrNotValidCertificateException_Exception, InvalidDateException_Exception, PasswordIsNotStrongException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPagedSourceSideTransactions", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.GetPagedSourceSideTransactions")
    @ResponseWrapper(localName = "getPagedSourceSideTransactionsResponse", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.GetPagedSourceSideTransactionsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PagedData getPagedSourceSideTransactions(

        @WebParam(name = "credential", targetNamespace = "")
        Credential credential,
        @WebParam(name = "sideTransactionsRequest", targetNamespace = "")
        SideTransactionsRequest sideTransactionsRequest,
        @WebParam(name = "paging", targetNamespace = "")
        Paging paging
    ) throws InvalidCredentialException_Exception, PasswordShouldBeChangeException_Exception, PageSizeIsTooMuchException_Exception, InvalidPageNumberException_Exception, UnableToAuthenticateException_Exception, InvalidTransactionTypeException_Exception, InvalidPageSizeException_Exception, InvalidCertificateException_Exception, UserTemporarilySuspendedException_Exception, UnableToGetClientCertificateInfo_Exception, ExpiredOrNotValidCertificateException_Exception, TransactionDoesNotBelongToAccount_Exception, PasswordIsNotStrongException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAccountControlType", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.GetAccountControlType")
    @ResponseWrapper(localName = "getAccountControlTypeResponse", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.GetAccountControlTypeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getAccountControlType(

        @WebParam(name = "credential", targetNamespace = "")
        Credential credential,
        @WebParam(name = "accountInfo", targetNamespace = "")
        AccountInfo accountInfo,
        @WebParam(name = "identifierType", targetNamespace = "")
        String identifierType
    ) throws InvalidCredentialException_Exception, UnableToAuthenticateException_Exception, PasswordShouldBeChangeException_Exception, InvalidCertificateException_Exception, UserTemporarilySuspendedException_Exception, ExpiredOrNotValidCertificateException_Exception, UnableToGetClientCertificateInfo_Exception, InvalidIdentifierTypeException_Exception, PasswordIsNotStrongException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMultipleAccountTransactionsDetails", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.GetMultipleAccountTransactionsDetails")
    @ResponseWrapper(localName = "getMultipleAccountTransactionsDetailsResponse", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.GetMultipleAccountTransactionsDetailsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PagedData getMultipleAccountTransactionsDetails(

        @WebParam(name = "credential", targetNamespace = "")
        Credential credential,
        @WebParam(name = "filter", targetNamespace = "")
        MultipleAccountTransactionFilter filter,
        @WebParam(name = "paging", targetNamespace = "")
        Paging paging
    ) throws InvalidCredentialException_Exception, PasswordShouldBeChangeException_Exception, TooMuchAccountsException_Exception, PageSizeIsTooMuchException_Exception, InvalidPageNumberException_Exception, UnableToAuthenticateException_Exception, InvalidPageSizeException_Exception, UnableToGetTransactionsException_Exception, InvalidCertificateException_Exception, UserTemporarilySuspendedException_Exception, UnableToGetClientCertificateInfo_Exception, ExpiredOrNotValidCertificateException_Exception, InvalidDateException_Exception, PasswordIsNotStrongException_Exception;

    @WebMethod
    @RequestWrapper(localName = "clearAccountControlType", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.ClearAccountControlType")
    @ResponseWrapper(localName = "clearAccountControlTypeResponse", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.ClearAccountControlTypeResponse")
    public void clearAccountControlType(

        @WebParam(name = "credential", targetNamespace = "")
        Credential credential,
        @WebParam(name = "accountInfo", targetNamespace = "")
        AccountInfo accountInfo,
        @WebParam(name = "identifierType", targetNamespace = "")
        String identifierType
    ) throws InvalidCredentialException_Exception, UnableToAuthenticateException_Exception, PasswordShouldBeChangeException_Exception, InvalidCertificateException_Exception, UserTemporarilySuspendedException_Exception, ExpiredOrNotValidCertificateException_Exception, UnableToGetClientCertificateInfo_Exception, InvalidIdentifierTypeException_Exception, PasswordIsNotStrongException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAccountNumbers", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.GetAccountNumbers")
    @ResponseWrapper(localName = "getAccountNumbersResponse", targetNamespace = "com.misc.bis.behdad.service", className = "edu.imi.ir.eduimiws.models.wsdl.behdad.GetAccountNumbersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<AccountInfo> getAccountNumbers(

        @WebParam(name = "credential", targetNamespace = "")
        Credential credential
    ) throws InvalidCredentialException_Exception, UnableToAuthenticateException_Exception, PasswordShouldBeChangeException_Exception, InvalidCertificateException_Exception, UserTemporarilySuspendedException_Exception, ExpiredOrNotValidCertificateException_Exception, UnableToGetClientCertificateInfo_Exception, PasswordIsNotStrongException_Exception;
}
