
package edu.imi.ir.eduimiws.models.wsdl.behdad;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-05-26T15:52:25.767+03:30
 * Generated source version: 3.6.5
 */

@WebFault(name = "ExpiredOrNotValidCertificateException", targetNamespace = "com.misc.bis.behdad.service")
public class ExpiredOrNotValidCertificateException_Exception extends Exception {

    private ExpiredOrNotValidCertificateException faultInfo;

    public ExpiredOrNotValidCertificateException_Exception() {
        super();
    }

    public ExpiredOrNotValidCertificateException_Exception(String message) {
        super(message);
    }

    public ExpiredOrNotValidCertificateException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ExpiredOrNotValidCertificateException_Exception(String message, ExpiredOrNotValidCertificateException expiredOrNotValidCertificateException) {
        super(message);
        this.faultInfo = expiredOrNotValidCertificateException;
    }

    public ExpiredOrNotValidCertificateException_Exception(String message, ExpiredOrNotValidCertificateException expiredOrNotValidCertificateException, Throwable cause) {
        super(message, cause);
        this.faultInfo = expiredOrNotValidCertificateException;
    }

    public ExpiredOrNotValidCertificateException getFaultInfo() {
        return this.faultInfo;
    }
}
