
package edu.imi.ir.eduimiws.models.wsdl.behdad;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-05-26T15:52:25.817+03:30
 * Generated source version: 3.6.5
 */

@WebFault(name = "InvalidPageSizeException", targetNamespace = "com.misc.bis.behdad.service")
public class InvalidPageSizeException_Exception extends Exception {

    private InvalidPageSizeException faultInfo;

    public InvalidPageSizeException_Exception() {
        super();
    }

    public InvalidPageSizeException_Exception(String message) {
        super(message);
    }

    public InvalidPageSizeException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidPageSizeException_Exception(String message, InvalidPageSizeException invalidPageSizeException) {
        super(message);
        this.faultInfo = invalidPageSizeException;
    }

    public InvalidPageSizeException_Exception(String message, InvalidPageSizeException invalidPageSizeException, Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidPageSizeException;
    }

    public InvalidPageSizeException getFaultInfo() {
        return this.faultInfo;
    }
}
