
package edu.imi.ir.eduimiws.models.wsdl.behdad;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-05-26T15:52:25.774+03:30
 * Generated source version: 3.6.5
 */

@WebFault(name = "InvalidIdentifierControlTypeException", targetNamespace = "com.misc.bis.behdad.service")
public class InvalidIdentifierControlTypeException_Exception extends Exception {

    private InvalidIdentifierControlTypeException faultInfo;

    public InvalidIdentifierControlTypeException_Exception() {
        super();
    }

    public InvalidIdentifierControlTypeException_Exception(String message) {
        super(message);
    }

    public InvalidIdentifierControlTypeException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidIdentifierControlTypeException_Exception(String message, InvalidIdentifierControlTypeException invalidIdentifierControlTypeException) {
        super(message);
        this.faultInfo = invalidIdentifierControlTypeException;
    }

    public InvalidIdentifierControlTypeException_Exception(String message, InvalidIdentifierControlTypeException invalidIdentifierControlTypeException, Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidIdentifierControlTypeException;
    }

    public InvalidIdentifierControlTypeException getFaultInfo() {
        return this.faultInfo;
    }
}
