
package edu.imi.ir.eduimiws.models.wsdl.behdad;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-05-26T15:52:25.811+03:30
 * Generated source version: 3.6.5
 */

@WebFault(name = "InvalidTransactionTypeException", targetNamespace = "com.misc.bis.behdad.service")
public class InvalidTransactionTypeException_Exception extends Exception {

    private InvalidTransactionTypeException faultInfo;

    public InvalidTransactionTypeException_Exception() {
        super();
    }

    public InvalidTransactionTypeException_Exception(String message) {
        super(message);
    }

    public InvalidTransactionTypeException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidTransactionTypeException_Exception(String message, InvalidTransactionTypeException invalidTransactionTypeException) {
        super(message);
        this.faultInfo = invalidTransactionTypeException;
    }

    public InvalidTransactionTypeException_Exception(String message, InvalidTransactionTypeException invalidTransactionTypeException, Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidTransactionTypeException;
    }

    public InvalidTransactionTypeException getFaultInfo() {
        return this.faultInfo;
    }
}
