
package edu.imi.ir.eduimiws.models.wsdl.behdad;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-05-26T15:52:25.747+03:30
 * Generated source version: 3.6.5
 */

@WebFault(name = "InvalidCertificateException", targetNamespace = "com.misc.bis.behdad.service")
public class InvalidCertificateException_Exception extends Exception {

    private InvalidCertificateException faultInfo;

    public InvalidCertificateException_Exception() {
        super();
    }

    public InvalidCertificateException_Exception(String message) {
        super(message);
    }

    public InvalidCertificateException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidCertificateException_Exception(String message, InvalidCertificateException invalidCertificateException) {
        super(message);
        this.faultInfo = invalidCertificateException;
    }

    public InvalidCertificateException_Exception(String message, InvalidCertificateException invalidCertificateException, Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidCertificateException;
    }

    public InvalidCertificateException getFaultInfo() {
        return this.faultInfo;
    }
}
