
package edu.imi.ir.eduimiws.models.wsdl.behdad;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-05-26T15:52:25.806+03:30
 * Generated source version: 3.6.5
 */

@WebFault(name = "InvalidPageNumberException", targetNamespace = "com.misc.bis.behdad.service")
public class InvalidPageNumberException_Exception extends Exception {

    private InvalidPageNumberException faultInfo;

    public InvalidPageNumberException_Exception() {
        super();
    }

    public InvalidPageNumberException_Exception(String message) {
        super(message);
    }

    public InvalidPageNumberException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidPageNumberException_Exception(String message, InvalidPageNumberException invalidPageNumberException) {
        super(message);
        this.faultInfo = invalidPageNumberException;
    }

    public InvalidPageNumberException_Exception(String message, InvalidPageNumberException invalidPageNumberException, Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidPageNumberException;
    }

    public InvalidPageNumberException getFaultInfo() {
        return this.faultInfo;
    }
}
