
package edu.imi.ir.eduimiws.models.wsdl.behdad;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-05-26T15:52:25.727+03:30
 * Generated source version: 3.6.5
 */

@WebFault(name = "InvalidCredentialException", targetNamespace = "com.misc.bis.behdad.service")
public class InvalidCredentialException_Exception extends Exception {

    private InvalidCredentialException faultInfo;

    public InvalidCredentialException_Exception() {
        super();
    }

    public InvalidCredentialException_Exception(String message) {
        super(message);
    }

    public InvalidCredentialException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidCredentialException_Exception(String message, InvalidCredentialException invalidCredentialException) {
        super(message);
        this.faultInfo = invalidCredentialException;
    }

    public InvalidCredentialException_Exception(String message, InvalidCredentialException invalidCredentialException, Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidCredentialException;
    }

    public InvalidCredentialException getFaultInfo() {
        return this.faultInfo;
    }
}
