
package edu.imi.ir.eduimiws.models.wsdl.behdad;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-05-26T15:52:25.801+03:30
 * Generated source version: 3.6.5
 */

@WebFault(name = "PageSizeIsTooMuchException", targetNamespace = "com.misc.bis.behdad.service")
public class PageSizeIsTooMuchException_Exception extends Exception {

    private PageSizeIsTooMuchException faultInfo;

    public PageSizeIsTooMuchException_Exception() {
        super();
    }

    public PageSizeIsTooMuchException_Exception(String message) {
        super(message);
    }

    public PageSizeIsTooMuchException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PageSizeIsTooMuchException_Exception(String message, PageSizeIsTooMuchException pageSizeIsTooMuchException) {
        super(message);
        this.faultInfo = pageSizeIsTooMuchException;
    }

    public PageSizeIsTooMuchException_Exception(String message, PageSizeIsTooMuchException pageSizeIsTooMuchException, Throwable cause) {
        super(message, cause);
        this.faultInfo = pageSizeIsTooMuchException;
    }

    public PageSizeIsTooMuchException getFaultInfo() {
        return this.faultInfo;
    }
}
