
package edu.imi.ir.eduimiws.models.wsdl.behdad;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-05-26T15:52:25.760+03:30
 * Generated source version: 3.6.5
 */

@WebFault(name = "UnableToGetClientCertificateInfo", targetNamespace = "com.misc.bis.behdad.service")
public class UnableToGetClientCertificateInfo_Exception extends Exception {

    private UnableToGetClientCertificateInfo faultInfo;

    public UnableToGetClientCertificateInfo_Exception() {
        super();
    }

    public UnableToGetClientCertificateInfo_Exception(String message) {
        super(message);
    }

    public UnableToGetClientCertificateInfo_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnableToGetClientCertificateInfo_Exception(String message, UnableToGetClientCertificateInfo unableToGetClientCertificateInfo) {
        super(message);
        this.faultInfo = unableToGetClientCertificateInfo;
    }

    public UnableToGetClientCertificateInfo_Exception(String message, UnableToGetClientCertificateInfo unableToGetClientCertificateInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = unableToGetClientCertificateInfo;
    }

    public UnableToGetClientCertificateInfo getFaultInfo() {
        return this.faultInfo;
    }
}
