
package edu.imi.ir.eduimiws.models.wsdl.behdad;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-05-26T15:52:25.797+03:30
 * Generated source version: 3.6.5
 */

@WebFault(name = "UnableToChangePasswordException", targetNamespace = "com.misc.bis.behdad.service")
public class UnableToChangePasswordException_Exception extends Exception {

    private UnableToChangePasswordException faultInfo;

    public UnableToChangePasswordException_Exception() {
        super();
    }

    public UnableToChangePasswordException_Exception(String message) {
        super(message);
    }

    public UnableToChangePasswordException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnableToChangePasswordException_Exception(String message, UnableToChangePasswordException unableToChangePasswordException) {
        super(message);
        this.faultInfo = unableToChangePasswordException;
    }

    public UnableToChangePasswordException_Exception(String message, UnableToChangePasswordException unableToChangePasswordException, Throwable cause) {
        super(message, cause);
        this.faultInfo = unableToChangePasswordException;
    }

    public UnableToChangePasswordException getFaultInfo() {
        return this.faultInfo;
    }
}
