
package edu.imi.ir.eduimiws.models.wsdl.behdad;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-05-26T15:52:25.733+03:30
 * Generated source version: 3.6.5
 */

@WebFault(name = "UnableToAuthenticateException", targetNamespace = "com.misc.bis.behdad.service")
public class UnableToAuthenticateException_Exception extends Exception {

    private UnableToAuthenticateException faultInfo;

    public UnableToAuthenticateException_Exception() {
        super();
    }

    public UnableToAuthenticateException_Exception(String message) {
        super(message);
    }

    public UnableToAuthenticateException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnableToAuthenticateException_Exception(String message, UnableToAuthenticateException unableToAuthenticateException) {
        super(message);
        this.faultInfo = unableToAuthenticateException;
    }

    public UnableToAuthenticateException_Exception(String message, UnableToAuthenticateException unableToAuthenticateException, Throwable cause) {
        super(message, cause);
        this.faultInfo = unableToAuthenticateException;
    }

    public UnableToAuthenticateException getFaultInfo() {
        return this.faultInfo;
    }
}
