package edu.imi.ir.eduimiws.models.request.edu.v1;


import com.fasterxml.jackson.annotation.JsonRootName;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.hateoas.server.core.Relation;

@Schema(name = "student", description = "Register student in application")
@JsonRootName(value = "student")
@Relation(collectionRelation = "students")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class StudentForm {

    @Schema(title = "National Code",
            description = "value use as USERNAME for login", maxLength = 20)
    private String personPublicId;

    @Schema(title = "First Name",
            description = "student first name", maxLength = 100)
    private String firstName;

    @Schema(title = "Last Name",
            description = "student last name", maxLength = 100)
    private String lastName;

    @Schema(title = "National Code",
            description = "student national code", maxLength = 15)
    private String nationCode;

    @Schema(title = "Code",
            description = "student code, generated by system", maxLength = 20)
    private String code;

    @Schema(title = "Activity Status",
            description = "student activity status")
    private Long activityStatus;

    @Schema(title = "Delete Status",
            description = "student delete status")
    private Long deleteStatus;

    @Schema(title = "creator public Id",
            description = "creator public Id", maxLength = 36)
    private String creatorPublicId;

    @Schema(title = "Create Date",
            description = "create date", maxLength = 10)
    private String createDate;

    @Schema(title = "editor public Id",
            description = "editor public Id", maxLength = 36)
    private String editorPublicId;

    @Schema(title = "edit date",
            description = "edit date", maxLength = 10)
    private String editDate;

    @Schema(title = "Description",
            description = "student description", maxLength = 150)
    private String description;

    @Schema(title = "Student public Id",
            description = "Student public Id", maxLength = 36)
    private String studentPublicId;
}
