
package edu.imi.ir.eduimiws.models.wsdl.attendance;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-01-08T14:55:53.890+03:30
 * Generated source version: 3.6.5
 *
 */
public final class EtsGeneralDataProviderServiceHttpGet_EtsGeneralDataProviderServiceHttpGet_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "EtsGeneralDataProviderService");

    private EtsGeneralDataProviderServiceHttpGet_EtsGeneralDataProviderServiceHttpGet_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = EtsGeneralDataProviderService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        EtsGeneralDataProviderService ss = new EtsGeneralDataProviderService(wsdlURL, SERVICE_NAME);
        EtsGeneralDataProviderServiceHttpGet port = ss.getEtsGeneralDataProviderServiceHttpGet();

        {
        System.out.println("Invoking addSpecialExtraWorkPermission...");
        String _addSpecialExtraWorkPermission_employeeCode = "";
        String _addSpecialExtraWorkPermission_value = "";
        String _addSpecialExtraWorkPermission_periodId = "";
        String _addSpecialExtraWorkPermission_requestReason = "";
        String _addSpecialExtraWorkPermission_description = "";
        String _addSpecialExtraWorkPermission_specialExtraWorkId = "";
        String _addSpecialExtraWorkPermission_organizationChartId = "";
        String _addSpecialExtraWorkPermission__return = port.addSpecialExtraWorkPermission(_addSpecialExtraWorkPermission_employeeCode, _addSpecialExtraWorkPermission_value, _addSpecialExtraWorkPermission_periodId, _addSpecialExtraWorkPermission_requestReason, _addSpecialExtraWorkPermission_description, _addSpecialExtraWorkPermission_specialExtraWorkId, _addSpecialExtraWorkPermission_organizationChartId);
        System.out.println("addSpecialExtraWorkPermission.result=" + _addSpecialExtraWorkPermission__return);


        }
        {
        System.out.println("Invoking addMissionRegistrationPermission...");
        String _addMissionRegistrationPermission_employeeCode = "";
        String _addMissionRegistrationPermission_missionId = "";
        String _addMissionRegistrationPermission_missionLocationId = "";
        String _addMissionRegistrationPermission_missionSubject = "";
        String _addMissionRegistrationPermission_beginDateTime = "";
        String _addMissionRegistrationPermission_endDateTime = "";
        String _addMissionRegistrationPermission_requestReason = "";
        String _addMissionRegistrationPermission_description = "";
        String _addMissionRegistrationPermission__return = port.addMissionRegistrationPermission(_addMissionRegistrationPermission_employeeCode, _addMissionRegistrationPermission_missionId, _addMissionRegistrationPermission_missionLocationId, _addMissionRegistrationPermission_missionSubject, _addMissionRegistrationPermission_beginDateTime, _addMissionRegistrationPermission_endDateTime, _addMissionRegistrationPermission_requestReason, _addMissionRegistrationPermission_description);
        System.out.println("addMissionRegistrationPermission.result=" + _addMissionRegistrationPermission__return);


        }
        {
        System.out.println("Invoking isValidPersonStringDate...");
        String _isValidPersonStringDate_employeeCode = "";
        String _isValidPersonStringDate_dateTime = "";
        String _isValidPersonStringDate_requestState = "";
        boolean _isValidPersonStringDate__return = port.isValidPersonStringDate(_isValidPersonStringDate_employeeCode, _isValidPersonStringDate_dateTime, _isValidPersonStringDate_requestState);
        System.out.println("isValidPersonStringDate.result=" + _isValidPersonStringDate__return);


        }
        {
        System.out.println("Invoking test...");
        String _test__return = port.test();
        System.out.println("test.result=" + _test__return);


        }
        {
        System.out.println("Invoking getIORecordPerPersistOn...");
        String _getIORecordPerPersistOn_fromDate = "";
        String _getIORecordPerPersistOn_toDate = "";
        ArrayOfIoRecordDataModel _getIORecordPerPersistOn__return = port.getIORecordPerPersistOn(_getIORecordPerPersistOn_fromDate, _getIORecordPerPersistOn_toDate);
        System.out.println("getIORecordPerPersistOn.result=" + _getIORecordPerPersistOn__return);


        }
        {
        System.out.println("Invoking getFunctionalityList...");
        String _getFunctionalityList_employeeCode = "";
        String _getFunctionalityList_fromDate = "";
        String _getFunctionalityList_toDate = "";
        ArrayOfString _getFunctionalityList__return = port.getFunctionalityList(_getFunctionalityList_employeeCode, _getFunctionalityList_fromDate, _getFunctionalityList_toDate);
        System.out.println("getFunctionalityList.result=" + _getFunctionalityList__return);


        }
        {
        System.out.println("Invoking addDailyExtraWorkPermission...");
        String _addDailyExtraWorkPermission_employeeCode = "";
        String _addDailyExtraWorkPermission_extraWorkId = "";
        String _addDailyExtraWorkPermission_beginDateTime = "";
        String _addDailyExtraWorkPermission_endDateTime = "";
        String _addDailyExtraWorkPermission_requestReason = "";
        String _addDailyExtraWorkPermission_description = "";
        String _addDailyExtraWorkPermission__return = port.addDailyExtraWorkPermission(_addDailyExtraWorkPermission_employeeCode, _addDailyExtraWorkPermission_extraWorkId, _addDailyExtraWorkPermission_beginDateTime, _addDailyExtraWorkPermission_endDateTime, _addDailyExtraWorkPermission_requestReason, _addDailyExtraWorkPermission_description);
        System.out.println("addDailyExtraWorkPermission.result=" + _addDailyExtraWorkPermission__return);


        }
        {
        System.out.println("Invoking getFunctionalityWinPayList...");
        String _getFunctionalityWinPayList_employeeCode = "";
        String _getFunctionalityWinPayList_date = "";
        String _getFunctionalityWinPayList_withVacation = "";
        String _getFunctionalityWinPayList_withSequenceWorkingDetails = "";
        String _getFunctionalityWinPayList_withSpecialExtraWork = "";
        String _getFunctionalityWinPayList_withVacationRemaining = "";
        String _getFunctionalityWinPayList_withSpecialAddSubVacation = "";
        String _getFunctionalityWinPayList_withMission = "";
        PeriodCalculationInfo _getFunctionalityWinPayList__return = port.getFunctionalityWinPayList(_getFunctionalityWinPayList_employeeCode, _getFunctionalityWinPayList_date, _getFunctionalityWinPayList_withVacation, _getFunctionalityWinPayList_withSequenceWorkingDetails, _getFunctionalityWinPayList_withSpecialExtraWork, _getFunctionalityWinPayList_withVacationRemaining, _getFunctionalityWinPayList_withSpecialAddSubVacation, _getFunctionalityWinPayList_withMission);
        System.out.println("getFunctionalityWinPayList.result=" + _getFunctionalityWinPayList__return);


        }
        {
        System.out.println("Invoking getAllCurrentlyEmployeesWithKey...");
        ArrayOfEmployeeDataModelWithKey _getAllCurrentlyEmployeesWithKey__return = port.getAllCurrentlyEmployeesWithKey();
        System.out.println("getAllCurrentlyEmployeesWithKey.result=" + _getAllCurrentlyEmployeesWithKey__return);


        }
        {
        System.out.println("Invoking getPeriodCalculationInfo...");
        String _getPeriodCalculationInfo_employeeCode = "";
        String _getPeriodCalculationInfo_fromDate = "";
        String _getPeriodCalculationInfo_toDate = "";
        port.getPeriodCalculationInfo(_getPeriodCalculationInfo_employeeCode, _getPeriodCalculationInfo_fromDate, _getPeriodCalculationInfo_toDate);


        }
        {
        System.out.println("Invoking isValidReserve...");
        String _isValidReserve_employeeCode = "";
        String _isValidReserve_startDateTime = "";
        String _isValidReserve_endDateTime = "";
        String _isValidReserve_officialHolidaySetting = "";
        String _isValidReserve_agreedHolidaySetting = "";
        String _isValidReserve_normalDaySetting = "";
        String _isValidReserve_chekExtraWorkPermission = "";
        boolean _isValidReserve__return = port.isValidReserve(_isValidReserve_employeeCode, _isValidReserve_startDateTime, _isValidReserve_endDateTime, _isValidReserve_officialHolidaySetting, _isValidReserve_agreedHolidaySetting, _isValidReserve_normalDaySetting, _isValidReserve_chekExtraWorkPermission);
        System.out.println("isValidReserve.result=" + _isValidReserve__return);


        }
        {
        System.out.println("Invoking isValidPerson...");
        String _isValidPerson_employeeCode = "";
        String _isValidPerson_dateTime = "";
        String _isValidPerson_requestState = "";
        String _isValidPerson_leaveHour = "";
        boolean _isValidPerson__return = port.isValidPerson(_isValidPerson_employeeCode, _isValidPerson_dateTime, _isValidPerson_requestState, _isValidPerson_leaveHour);
        System.out.println("isValidPerson.result=" + _isValidPerson__return);


        }
        {
        System.out.println("Invoking getOrganizationChartIdByEmployeeById...");
        String _getOrganizationChartIdByEmployeeById_regionId = "";
        String _getOrganizationChartIdByEmployeeById_employeeId = "";
        long _getOrganizationChartIdByEmployeeById__return = port.getOrganizationChartIdByEmployeeById(_getOrganizationChartIdByEmployeeById_regionId, _getOrganizationChartIdByEmployeeById_employeeId);
        System.out.println("getOrganizationChartIdByEmployeeById.result=" + _getOrganizationChartIdByEmployeeById__return);


        }
        {
        System.out.println("Invoking getAllExtraWorkPermissionsByDate...");
        String _getAllExtraWorkPermissionsByDate_date = "";
        ArrayOfDailyExtraWorkPermissionDataModel _getAllExtraWorkPermissionsByDate__return = port.getAllExtraWorkPermissionsByDate(_getAllExtraWorkPermissionsByDate_date);
        System.out.println("getAllExtraWorkPermissionsByDate.result=" + _getAllExtraWorkPermissionsByDate__return);


        }
        {
        System.out.println("Invoking getDailyMissionsOrVacations...");
        String _getDailyMissionsOrVacations_startDateTime = "";
        String _getDailyMissionsOrVacations_endDateTime = "";
        String _getDailyMissionsOrVacations__return = port.getDailyMissionsOrVacations(_getDailyMissionsOrVacations_startDateTime, _getDailyMissionsOrVacations_endDateTime);
        System.out.println("getDailyMissionsOrVacations.result=" + _getDailyMissionsOrVacations__return);


        }
        {
        System.out.println("Invoking getAllEmployeesInfo...");
        ArrayOfEmployeeInfo _getAllEmployeesInfo__return = port.getAllEmployeesInfo();
        System.out.println("getAllEmployeesInfo.result=" + _getAllEmployeesInfo__return);


        }
        {
        System.out.println("Invoking addMissionRegistration...");
        String _addMissionRegistration_employeeCode = "";
        String _addMissionRegistration_missionId = "";
        String _addMissionRegistration_beginDateTime = "";
        String _addMissionRegistration_endDateTime = "";
        String _addMissionRegistration__return = port.addMissionRegistration(_addMissionRegistration_employeeCode, _addMissionRegistration_missionId, _addMissionRegistration_beginDateTime, _addMissionRegistration_endDateTime);
        System.out.println("addMissionRegistration.result=" + _addMissionRegistration__return);


        }
        {
        System.out.println("Invoking getIoSources...");
        ArrayOfString _getIoSources__return = port.getIoSources();
        System.out.println("getIoSources.result=" + _getIoSources__return);


        }
        {
        System.out.println("Invoking getEmployeeFullNameFromLoginResult...");
        String _getEmployeeFullNameFromLoginResult_userName = "";
        String _getEmployeeFullNameFromLoginResult_password = "";
        String _getEmployeeFullNameFromLoginResult__return = port.getEmployeeFullNameFromLoginResult(_getEmployeeFullNameFromLoginResult_userName, _getEmployeeFullNameFromLoginResult_password);
        System.out.println("getEmployeeFullNameFromLoginResult.result=" + _getEmployeeFullNameFromLoginResult__return);


        }
        {
        System.out.println("Invoking getUiRequestCartableIds...");
        String _getUiRequestCartableIds_employeeCode = "";
        UiRequestCartableIds _getUiRequestCartableIds__return = port.getUiRequestCartableIds(_getUiRequestCartableIds_employeeCode);
        System.out.println("getUiRequestCartableIds.result=" + _getUiRequestCartableIds__return);


        }
        {
        System.out.println("Invoking getCalendarWorkDayTypesByEmployee...");
        String _getCalendarWorkDayTypesByEmployee_employeeCode = "";
        String _getCalendarWorkDayTypesByEmployee_fromDate = "";
        String _getCalendarWorkDayTypesByEmployee_toDate = "";
        ArrayOfCalendarDayListDto _getCalendarWorkDayTypesByEmployee__return = port.getCalendarWorkDayTypesByEmployee(_getCalendarWorkDayTypesByEmployee_employeeCode, _getCalendarWorkDayTypesByEmployee_fromDate, _getCalendarWorkDayTypesByEmployee_toDate);
        System.out.println("getCalendarWorkDayTypesByEmployee.result=" + _getCalendarWorkDayTypesByEmployee__return);


        }
        {
        System.out.println("Invoking getAllEmployeesWithOrgId...");
        ArrayOfEmployeeInfo _getAllEmployeesWithOrgId__return = port.getAllEmployeesWithOrgId();
        System.out.println("getAllEmployeesWithOrgId.result=" + _getAllEmployeesWithOrgId__return);


        }
        {
        System.out.println("Invoking getAllPeriodFunctionalityWinPayList...");
        String _getAllPeriodFunctionalityWinPayList_employeeCode = "";
        String _getAllPeriodFunctionalityWinPayList_date = "";
        String _getAllPeriodFunctionalityWinPayList_withVacation = "";
        String _getAllPeriodFunctionalityWinPayList_withSequenceWorkingDetails = "";
        String _getAllPeriodFunctionalityWinPayList_withSpecialExtraWork = "";
        String _getAllPeriodFunctionalityWinPayList_withVacationRemaining = "";
        String _getAllPeriodFunctionalityWinPayList_withSpecialAddSubVacation = "";
        String _getAllPeriodFunctionalityWinPayList_withMission = "";
        ArrayOfPeriodCalculationInfo _getAllPeriodFunctionalityWinPayList__return = port.getAllPeriodFunctionalityWinPayList(_getAllPeriodFunctionalityWinPayList_employeeCode, _getAllPeriodFunctionalityWinPayList_date, _getAllPeriodFunctionalityWinPayList_withVacation, _getAllPeriodFunctionalityWinPayList_withSequenceWorkingDetails, _getAllPeriodFunctionalityWinPayList_withSpecialExtraWork, _getAllPeriodFunctionalityWinPayList_withVacationRemaining, _getAllPeriodFunctionalityWinPayList_withSpecialAddSubVacation, _getAllPeriodFunctionalityWinPayList_withMission);
        System.out.println("getAllPeriodFunctionalityWinPayList.result=" + _getAllPeriodFunctionalityWinPayList__return);


        }
        {
        System.out.println("Invoking getOrganizationChartList...");
        String _getOrganizationChartList_regionId = "";
        ArrayOfString _getOrganizationChartList__return = port.getOrganizationChartList(_getOrganizationChartList_regionId);
        System.out.println("getOrganizationChartList.result=" + _getOrganizationChartList__return);


        }
        {
        System.out.println("Invoking getValidCardList...");
        String _getValidCardList_regionId = "";
        ArrayOfString _getValidCardList__return = port.getValidCardList(_getValidCardList_regionId);
        System.out.println("getValidCardList.result=" + _getValidCardList__return);


        }
        {
        System.out.println("Invoking getAllVacationRegistrationsByDate...");
        String _getAllVacationRegistrationsByDate_date = "";
        ArrayOfVacationRegistrationDataModel _getAllVacationRegistrationsByDate__return = port.getAllVacationRegistrationsByDate(_getAllVacationRegistrationsByDate_date);
        System.out.println("getAllVacationRegistrationsByDate.result=" + _getAllVacationRegistrationsByDate__return);


        }
        {
        System.out.println("Invoking getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId...");
        String _getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId_currentOrganizationchartId = "";
        ArrayOfOrganizationChartDataModel _getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId__return = port.getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId(_getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId_currentOrganizationchartId);
        System.out.println("getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId.result=" + _getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId__return);


        }
        {
        System.out.println("Invoking getAllMissionRegistrationsByDate...");
        String _getAllMissionRegistrationsByDate_date = "";
        ArrayOfMissionRegistrationDataModel _getAllMissionRegistrationsByDate__return = port.getAllMissionRegistrationsByDate(_getAllMissionRegistrationsByDate_date);
        System.out.println("getAllMissionRegistrationsByDate.result=" + _getAllMissionRegistrationsByDate__return);


        }
        {
        System.out.println("Invoking getIoRecordInDayByEmployeeCode...");
        String _getIoRecordInDayByEmployeeCode_employeeCode = "";
        String _getIoRecordInDayByEmployeeCode_dayDate = "";
        ArrayOfStaffIOs _getIoRecordInDayByEmployeeCode__return = port.getIoRecordInDayByEmployeeCode(_getIoRecordInDayByEmployeeCode_employeeCode, _getIoRecordInDayByEmployeeCode_dayDate);
        System.out.println("getIoRecordInDayByEmployeeCode.result=" + _getIoRecordInDayByEmployeeCode__return);


        }
        {
        System.out.println("Invoking checkTimeAttendanceSystemHasThirdPartyWebServicec...");
        boolean _checkTimeAttendanceSystemHasThirdPartyWebServicec__return = port.checkTimeAttendanceSystemHasThirdPartyWebServicec();
        System.out.println("checkTimeAttendanceSystemHasThirdPartyWebServicec.result=" + _checkTimeAttendanceSystemHasThirdPartyWebServicec__return);


        }
        {
        System.out.println("Invoking getAllOrganizationChartList...");
        ArrayOfOrganizationChartDataModel _getAllOrganizationChartList__return = port.getAllOrganizationChartList();
        System.out.println("getAllOrganizationChartList.result=" + _getAllOrganizationChartList__return);


        }
        {
        System.out.println("Invoking getAllEmployees...");
        ArrayOfEmployeeDataModel _getAllEmployees__return = port.getAllEmployees();
        System.out.println("getAllEmployees.result=" + _getAllEmployees__return);


        }
        {
        System.out.println("Invoking getRemainUiEmployeeVacationTypeRepositoryList...");
        String _getRemainUiEmployeeVacationTypeRepositoryList_employeeCode = "";
        String _getRemainUiEmployeeVacationTypeRepositoryList_currentWorkingYear = "";
        ArrayOfString _getRemainUiEmployeeVacationTypeRepositoryList__return = port.getRemainUiEmployeeVacationTypeRepositoryList(_getRemainUiEmployeeVacationTypeRepositoryList_employeeCode, _getRemainUiEmployeeVacationTypeRepositoryList_currentWorkingYear);
        System.out.println("getRemainUiEmployeeVacationTypeRepositoryList.result=" + _getRemainUiEmployeeVacationTypeRepositoryList__return);


        }
        {
        System.out.println("Invoking getAllSpecialExtraWorksByPeriodId...");
        String _getAllSpecialExtraWorksByPeriodId_periodId = "";
        ArrayOfSpecialExtraWorkDataModel _getAllSpecialExtraWorksByPeriodId__return = port.getAllSpecialExtraWorksByPeriodId(_getAllSpecialExtraWorksByPeriodId_periodId);
        System.out.println("getAllSpecialExtraWorksByPeriodId.result=" + _getAllSpecialExtraWorksByPeriodId__return);


        }
        {
        System.out.println("Invoking getEmployeeCodeByKeyNumber...");
        String _getEmployeeCodeByKeyNumber_keyNumber = "";
        String _getEmployeeCodeByKeyNumber_gregorianDate = "";
        String _getEmployeeCodeByKeyNumber_shamsiDate = "";
        String _getEmployeeCodeByKeyNumber_systemType = "";
        String _getEmployeeCodeByKeyNumber_deviceModuleType = "";
        String _getEmployeeCodeByKeyNumber__return = port.getEmployeeCodeByKeyNumber(_getEmployeeCodeByKeyNumber_keyNumber, _getEmployeeCodeByKeyNumber_gregorianDate, _getEmployeeCodeByKeyNumber_shamsiDate, _getEmployeeCodeByKeyNumber_systemType, _getEmployeeCodeByKeyNumber_deviceModuleType);
        System.out.println("getEmployeeCodeByKeyNumber.result=" + _getEmployeeCodeByKeyNumber__return);


        }
        {
        System.out.println("Invoking getIsExitOverTimeList...");
        String _getIsExitOverTimeList_perno = "";
        String _getIsExitOverTimeList_time = "";
        String _getIsExitOverTimeList_startDate = "";
        String _getIsExitOverTimeList_endDate = "";
        boolean _getIsExitOverTimeList__return = port.getIsExitOverTimeList(_getIsExitOverTimeList_perno, _getIsExitOverTimeList_time, _getIsExitOverTimeList_startDate, _getIsExitOverTimeList_endDate);
        System.out.println("getIsExitOverTimeList.result=" + _getIsExitOverTimeList__return);


        }
        {
        System.out.println("Invoking getOrganizationChartIdByEmployee...");
        String _getOrganizationChartIdByEmployee_regionId = "";
        String _getOrganizationChartIdByEmployee_employeeId = "";
        long _getOrganizationChartIdByEmployee__return = port.getOrganizationChartIdByEmployee(_getOrganizationChartIdByEmployee_regionId, _getOrganizationChartIdByEmployee_employeeId);
        System.out.println("getOrganizationChartIdByEmployee.result=" + _getOrganizationChartIdByEmployee__return);


        }
        {
        System.out.println("Invoking getDayCalculationInfo...");
        String _getDayCalculationInfo_employeeCode = "";
        String _getDayCalculationInfo_fromDate = "";
        String _getDayCalculationInfo_toDate = "";
        port.getDayCalculationInfo(_getDayCalculationInfo_employeeCode, _getDayCalculationInfo_fromDate, _getDayCalculationInfo_toDate);


        }
        {
        System.out.println("Invoking getListOfEmployeeEvents...");
        String _getListOfEmployeeEvents_employeeEvent = "";
        ArrayOfEmployeeDataModel _getListOfEmployeeEvents__return = port.getListOfEmployeeEvents(_getListOfEmployeeEvents_employeeEvent);
        System.out.println("getListOfEmployeeEvents.result=" + _getListOfEmployeeEvents__return);


        }
        {
        System.out.println("Invoking addVacationRegistration...");
        String _addVacationRegistration_employeeCode = "";
        String _addVacationRegistration_vacationId = "";
        String _addVacationRegistration_beginDateTime = "";
        String _addVacationRegistration_endDateTime = "";
        String _addVacationRegistration__return = port.addVacationRegistration(_addVacationRegistration_employeeCode, _addVacationRegistration_vacationId, _addVacationRegistration_beginDateTime, _addVacationRegistration_endDateTime);
        System.out.println("addVacationRegistration.result=" + _addVacationRegistration__return);


        }
        {
        System.out.println("Invoking getAllCurrentlyEmployees...");
        ArrayOfEmployeeDataModel _getAllCurrentlyEmployees__return = port.getAllCurrentlyEmployees();
        System.out.println("getAllCurrentlyEmployees.result=" + _getAllCurrentlyEmployees__return);


        }
        {
        System.out.println("Invoking getAllEmployeesOfOneOrganizationChartWithAllSubsets...");
        String _getAllEmployeesOfOneOrganizationChartWithAllSubsets_currentOrganizationchartId = "";
        ArrayOfEmployeeDataModel _getAllEmployeesOfOneOrganizationChartWithAllSubsets__return = port.getAllEmployeesOfOneOrganizationChartWithAllSubsets(_getAllEmployeesOfOneOrganizationChartWithAllSubsets_currentOrganizationchartId);
        System.out.println("getAllEmployeesOfOneOrganizationChartWithAllSubsets.result=" + _getAllEmployeesOfOneOrganizationChartWithAllSubsets__return);


        }
        {
        System.out.println("Invoking getIORecordAfterId...");
        String _getIORecordAfterId_id = "";
        ArrayOfIoRecordDataModel _getIORecordAfterId__return = port.getIORecordAfterId(_getIORecordAfterId_id);
        System.out.println("getIORecordAfterId.result=" + _getIORecordAfterId__return);


        }
        {
        System.out.println("Invoking isPresent...");
        String _isPresent_id = "";
        String _isPresent_dateTime = "";
        boolean _isPresent__return = port.isPresent(_isPresent_id, _isPresent_dateTime);
        System.out.println("isPresent.result=" + _isPresent__return);


        }
        {
        System.out.println("Invoking getDevicePersons...");
        String _getDevicePersons_deviceModuleType = "";
        ArrayOfDevicePerson _getDevicePersons__return = port.getDevicePersons(_getDevicePersons_deviceModuleType);
        System.out.println("getDevicePersons.result=" + _getDevicePersons__return);


        }
        {
        System.out.println("Invoking getAllIoRecordsByDate...");
        String _getAllIoRecordsByDate_date = "";
        ArrayOfIoRecordDataModel _getAllIoRecordsByDate__return = port.getAllIoRecordsByDate(_getAllIoRecordsByDate_date);
        System.out.println("getAllIoRecordsByDate.result=" + _getAllIoRecordsByDate__return);


        }
        {
        System.out.println("Invoking getUiRequestCartableCount...");
        String _getUiRequestCartableCount_employeeCode = "";
        String _getUiRequestCartableCount__return = port.getUiRequestCartableCount(_getUiRequestCartableCount_employeeCode);
        System.out.println("getUiRequestCartableCount.result=" + _getUiRequestCartableCount__return);


        }
        {
        System.out.println("Invoking getRemainUiEmployeeVacationTypeRepository...");
        String _getRemainUiEmployeeVacationTypeRepository_employeeCode = "";
        String _getRemainUiEmployeeVacationTypeRepository_vacationtypeId = "";
        String _getRemainUiEmployeeVacationTypeRepository__return = port.getRemainUiEmployeeVacationTypeRepository(_getRemainUiEmployeeVacationTypeRepository_employeeCode, _getRemainUiEmployeeVacationTypeRepository_vacationtypeId);
        System.out.println("getRemainUiEmployeeVacationTypeRepository.result=" + _getRemainUiEmployeeVacationTypeRepository__return);


        }
        {
        System.out.println("Invoking getAllValidEmployeeRange...");
        String _getAllValidEmployeeRange_dateTime = "";
        String _getAllValidEmployeeRange_requestState = "";
        ArrayOfValidEmployeeRange _getAllValidEmployeeRange__return = port.getAllValidEmployeeRange(_getAllValidEmployeeRange_dateTime, _getAllValidEmployeeRange_requestState);
        System.out.println("getAllValidEmployeeRange.result=" + _getAllValidEmployeeRange__return);


        }
        {
        System.out.println("Invoking getIORecordPerDateRange...");
        String _getIORecordPerDateRange_fromDate = "";
        String _getIORecordPerDateRange_toDate = "";
        ArrayOfIoRecordDataModel _getIORecordPerDateRange__return = port.getIORecordPerDateRange(_getIORecordPerDateRange_fromDate, _getIORecordPerDateRange_toDate);
        System.out.println("getIORecordPerDateRange.result=" + _getIORecordPerDateRange__return);


        }
        {
        System.out.println("Invoking getCalendarWorkDayTypes...");
        String _getCalendarWorkDayTypes_calendarName = "";
        String _getCalendarWorkDayTypes_fromDate = "";
        String _getCalendarWorkDayTypes_toDate = "";
        ArrayOfCalendarDayListDto _getCalendarWorkDayTypes__return = port.getCalendarWorkDayTypes(_getCalendarWorkDayTypes_calendarName, _getCalendarWorkDayTypes_fromDate, _getCalendarWorkDayTypes_toDate);
        System.out.println("getCalendarWorkDayTypes.result=" + _getCalendarWorkDayTypes__return);


        }
        {
        System.out.println("Invoking addMissionRegistrationEx...");
        String _addMissionRegistrationEx_employeeCode = "";
        String _addMissionRegistrationEx_confirmEmployeeCode = "";
        String _addMissionRegistrationEx_missionId = "";
        String _addMissionRegistrationEx_beginDateTime = "";
        String _addMissionRegistrationEx_endDateTime = "";
        String _addMissionRegistrationEx_missionLocationName = "";
        String _addMissionRegistrationEx__return = port.addMissionRegistrationEx(_addMissionRegistrationEx_employeeCode, _addMissionRegistrationEx_confirmEmployeeCode, _addMissionRegistrationEx_missionId, _addMissionRegistrationEx_beginDateTime, _addMissionRegistrationEx_endDateTime, _addMissionRegistrationEx_missionLocationName);
        System.out.println("addMissionRegistrationEx.result=" + _addMissionRegistrationEx__return);


        }
        {
        System.out.println("Invoking addVacationRegistrationPermission...");
        String _addVacationRegistrationPermission_employeeCode = "";
        String _addVacationRegistrationPermission_vacationId = "";
        String _addVacationRegistrationPermission_beginDateTime = "";
        String _addVacationRegistrationPermission_endDateTime = "";
        String _addVacationRegistrationPermission_vacationRequestReason = "";
        String _addVacationRegistrationPermission_description = "";
        String _addVacationRegistrationPermission__return = port.addVacationRegistrationPermission(_addVacationRegistrationPermission_employeeCode, _addVacationRegistrationPermission_vacationId, _addVacationRegistrationPermission_beginDateTime, _addVacationRegistrationPermission_endDateTime, _addVacationRegistrationPermission_vacationRequestReason, _addVacationRegistrationPermission_description);
        System.out.println("addVacationRegistrationPermission.result=" + _addVacationRegistrationPermission__return);


        }
        {
        System.out.println("Invoking persistIoRecrd...");
        String _persistIoRecrd_keyNumber = "";
        String _persistIoRecrd_ioDateTime = "";
        String _persistIoRecrd_deviceModuleType = "";
        String _persistIoRecrd_hadwareCode = "";
        boolean _persistIoRecrd__return = port.persistIoRecrd(_persistIoRecrd_keyNumber, _persistIoRecrd_ioDateTime, _persistIoRecrd_deviceModuleType, _persistIoRecrd_hadwareCode);
        System.out.println("persistIoRecrd.result=" + _persistIoRecrd__return);


        }

        System.exit(0);
    }

}
