package edu.imi.ir.eduimiws.models.wsdl.attendance;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.0
 * 2025-01-31T12:06:54.479+03:30
 * Generated source version: 4.1.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "EtsGeneralDataProviderServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface EtsGeneralDataProviderServiceSoap {

    @WebMethod(operationName = "AddSpecialExtraWorkPermission", action = "http://tempuri.org/AddSpecialExtraWorkPermission")
    @RequestWrapper(localName = "AddSpecialExtraWorkPermission", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.AddSpecialExtraWorkPermission")
    @ResponseWrapper(localName = "AddSpecialExtraWorkPermissionResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.AddSpecialExtraWorkPermissionResponse")
    @WebResult(name = "AddSpecialExtraWorkPermissionResult", targetNamespace = "http://tempuri.org/")
    public String addSpecialExtraWorkPermission(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "value", targetNamespace = "http://tempuri.org/")
        int value,
        @WebParam(name = "periodId", targetNamespace = "http://tempuri.org/")
        long periodId,
        @WebParam(name = "requestReason", targetNamespace = "http://tempuri.org/")
        String requestReason,
        @WebParam(name = "description", targetNamespace = "http://tempuri.org/")
        String description,
        @WebParam(name = "specialExtraWorkId", targetNamespace = "http://tempuri.org/")
        long specialExtraWorkId,
        @WebParam(name = "organizationChartId", targetNamespace = "http://tempuri.org/")
        long organizationChartId
    );

    @WebMethod(operationName = "AddMissionRegistrationPermission", action = "http://tempuri.org/AddMissionRegistrationPermission")
    @RequestWrapper(localName = "AddMissionRegistrationPermission", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.AddMissionRegistrationPermission")
    @ResponseWrapper(localName = "AddMissionRegistrationPermissionResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.AddMissionRegistrationPermissionResponse")
    @WebResult(name = "AddMissionRegistrationPermissionResult", targetNamespace = "http://tempuri.org/")
    public String addMissionRegistrationPermission(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "missionId", targetNamespace = "http://tempuri.org/")
        long missionId,
        @WebParam(name = "missionLocationId", targetNamespace = "http://tempuri.org/")
        long missionLocationId,
        @WebParam(name = "missionSubject", targetNamespace = "http://tempuri.org/")
        String missionSubject,
        @WebParam(name = "beginDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime,
        @WebParam(name = "requestReason", targetNamespace = "http://tempuri.org/")
        String requestReason,
        @WebParam(name = "description", targetNamespace = "http://tempuri.org/")
        String description
    );

    @WebMethod(operationName = "IsValidPersonStringDate", action = "http://tempuri.org/IsValidPersonStringDate")
    @RequestWrapper(localName = "IsValidPersonStringDate", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.IsValidPersonStringDate")
    @ResponseWrapper(localName = "IsValidPersonStringDateResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.IsValidPersonStringDateResponse")
    @WebResult(name = "IsValidPersonStringDateResult", targetNamespace = "http://tempuri.org/")
    public boolean isValidPersonStringDate(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "dateTime", targetNamespace = "http://tempuri.org/")
        String dateTime,
        @WebParam(name = "requestState", targetNamespace = "http://tempuri.org/")
        int requestState
    );

    @WebMethod(operationName = "Test", action = "http://tempuri.org/Test")
    @RequestWrapper(localName = "Test", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.Test")
    @ResponseWrapper(localName = "TestResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.TestResponse")
    @WebResult(name = "TestResult", targetNamespace = "http://tempuri.org/")
    public String test()
;

    @WebMethod(operationName = "GetIORecordPerPersistOn", action = "http://tempuri.org/GetIORecordPerPersistOn")
    @RequestWrapper(localName = "GetIORecordPerPersistOn", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetIORecordPerPersistOn")
    @ResponseWrapper(localName = "GetIORecordPerPersistOnResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetIORecordPerPersistOnResponse")
    @WebResult(name = "GetIORecordPerPersistOnResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfIoRecordDataModel getIORecordPerPersistOn(

        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        String toDate
    );

    @WebMethod(operationName = "GetFunctionalityList", action = "http://tempuri.org/GetFunctionalityList")
    @RequestWrapper(localName = "GetFunctionalityList", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetFunctionalityList")
    @ResponseWrapper(localName = "GetFunctionalityListResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetFunctionalityListResponse")
    @WebResult(name = "GetFunctionalityListResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfString getFunctionalityList(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "AddDailyExtraWorkPermission", action = "http://tempuri.org/AddDailyExtraWorkPermission")
    @RequestWrapper(localName = "AddDailyExtraWorkPermission", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.AddDailyExtraWorkPermission")
    @ResponseWrapper(localName = "AddDailyExtraWorkPermissionResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.AddDailyExtraWorkPermissionResponse")
    @WebResult(name = "AddDailyExtraWorkPermissionResult", targetNamespace = "http://tempuri.org/")
    public String addDailyExtraWorkPermission(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "extraWorkId", targetNamespace = "http://tempuri.org/")
        long extraWorkId,
        @WebParam(name = "beginDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime,
        @WebParam(name = "requestReason", targetNamespace = "http://tempuri.org/")
        String requestReason,
        @WebParam(name = "description", targetNamespace = "http://tempuri.org/")
        String description
    );

    @WebMethod(operationName = "GetFunctionalityWinPayList", action = "http://tempuri.org/GetFunctionalityWinPayList")
    @RequestWrapper(localName = "GetFunctionalityWinPayList", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetFunctionalityWinPayList")
    @ResponseWrapper(localName = "GetFunctionalityWinPayListResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetFunctionalityWinPayListResponse")
    @WebResult(name = "GetFunctionalityWinPayListResult", targetNamespace = "http://tempuri.org/")
    public PeriodCalculationInfo getFunctionalityWinPayList(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar date,
        @WebParam(name = "withVacation", targetNamespace = "http://tempuri.org/")
        boolean withVacation,
        @WebParam(name = "withSequenceWorkingDetails", targetNamespace = "http://tempuri.org/")
        boolean withSequenceWorkingDetails,
        @WebParam(name = "withSpecialExtraWork", targetNamespace = "http://tempuri.org/")
        boolean withSpecialExtraWork,
        @WebParam(name = "withVacationRemaining", targetNamespace = "http://tempuri.org/")
        boolean withVacationRemaining,
        @WebParam(name = "withSpecialAddSubVacation", targetNamespace = "http://tempuri.org/")
        boolean withSpecialAddSubVacation,
        @WebParam(name = "withMission", targetNamespace = "http://tempuri.org/")
        boolean withMission
    );

    @WebMethod(operationName = "GetAllCurrentlyEmployeesWithKey", action = "http://tempuri.org/GetAllCurrentlyEmployeesWithKey")
    @RequestWrapper(localName = "GetAllCurrentlyEmployeesWithKey", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllCurrentlyEmployeesWithKey")
    @ResponseWrapper(localName = "GetAllCurrentlyEmployeesWithKeyResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllCurrentlyEmployeesWithKeyResponse")
    @WebResult(name = "GetAllCurrentlyEmployeesWithKeyResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfEmployeeDataModelWithKey getAllCurrentlyEmployeesWithKey()
;

    @WebMethod(operationName = "GetPeriodCalculationInfo", action = "http://tempuri.org/GetPeriodCalculationInfo")
    @RequestWrapper(localName = "GetPeriodCalculationInfo", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetPeriodCalculationInfo")
    @ResponseWrapper(localName = "GetPeriodCalculationInfoResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetPeriodCalculationInfoResponse")
    public void getPeriodCalculationInfo(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "IsValidReserve", action = "http://tempuri.org/IsValidReserve")
    @RequestWrapper(localName = "IsValidReserve", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.IsValidReserve")
    @ResponseWrapper(localName = "IsValidReserveResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.IsValidReserveResponse")
    @WebResult(name = "IsValidReserveResult", targetNamespace = "http://tempuri.org/")
    public boolean isValidReserve(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "startDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar startDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime,
        @WebParam(name = "officialHolidaySetting", targetNamespace = "http://tempuri.org/")
        String officialHolidaySetting,
        @WebParam(name = "agreedHolidaySetting", targetNamespace = "http://tempuri.org/")
        String agreedHolidaySetting,
        @WebParam(name = "normalDaySetting", targetNamespace = "http://tempuri.org/")
        String normalDaySetting,
        @WebParam(name = "chekExtraWorkPermission", targetNamespace = "http://tempuri.org/")
        boolean chekExtraWorkPermission
    );

    @WebMethod(operationName = "IsValidPerson", action = "http://tempuri.org/IsValidPerson")
    @RequestWrapper(localName = "IsValidPerson", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.IsValidPerson")
    @ResponseWrapper(localName = "IsValidPersonResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.IsValidPersonResponse")
    @WebResult(name = "IsValidPersonResult", targetNamespace = "http://tempuri.org/")
    public boolean isValidPerson(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "dateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar dateTime,
        @WebParam(name = "requestState", targetNamespace = "http://tempuri.org/")
        int requestState,
        @WebParam(name = "leaveHour", targetNamespace = "http://tempuri.org/")
        String leaveHour
    );

    @WebMethod(operationName = "GetOrganizationChartIdByEmployeeById", action = "http://tempuri.org/GetOrganizationChartIdByEmployeeById")
    @RequestWrapper(localName = "GetOrganizationChartIdByEmployeeById", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetOrganizationChartIdByEmployeeById")
    @ResponseWrapper(localName = "GetOrganizationChartIdByEmployeeByIdResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetOrganizationChartIdByEmployeeByIdResponse")
    @WebResult(name = "GetOrganizationChartIdByEmployeeByIdResult", targetNamespace = "http://tempuri.org/")
    public Long getOrganizationChartIdByEmployeeById(

        @WebParam(name = "regionId", targetNamespace = "http://tempuri.org/")
        long regionId,
        @WebParam(name = "employeeId", targetNamespace = "http://tempuri.org/")
        long employeeId
    );

    @WebMethod(operationName = "GetAllExtraWorkPermissionsByDate", action = "http://tempuri.org/GetAllExtraWorkPermissionsByDate")
    @RequestWrapper(localName = "GetAllExtraWorkPermissionsByDate", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllExtraWorkPermissionsByDate")
    @ResponseWrapper(localName = "GetAllExtraWorkPermissionsByDateResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllExtraWorkPermissionsByDateResponse")
    @WebResult(name = "GetAllExtraWorkPermissionsByDateResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfDailyExtraWorkPermissionDataModel getAllExtraWorkPermissionsByDate(

        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        String date
    );

    @WebMethod(operationName = "GetDailyMissionsOrVacations", action = "http://tempuri.org/GetDailyMissionsOrVacations")
    @RequestWrapper(localName = "GetDailyMissionsOrVacations", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetDailyMissionsOrVacations")
    @ResponseWrapper(localName = "GetDailyMissionsOrVacationsResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetDailyMissionsOrVacationsResponse")
    @WebResult(name = "GetDailyMissionsOrVacationsResult", targetNamespace = "http://tempuri.org/")
    public String getDailyMissionsOrVacations(

        @WebParam(name = "startDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar startDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime
    );

    @WebMethod(operationName = "GetAllEmployeesInfo", action = "http://tempuri.org/GetAllEmployeesInfo")
    @RequestWrapper(localName = "GetAllEmployeesInfo", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllEmployeesInfo")
    @ResponseWrapper(localName = "GetAllEmployeesInfoResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllEmployeesInfoResponse")
    @WebResult(name = "GetAllEmployeesInfoResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfEmployeeInfo getAllEmployeesInfo()
;

    @WebMethod(operationName = "AddMissionRegistration", action = "http://tempuri.org/AddMissionRegistration")
    @RequestWrapper(localName = "AddMissionRegistration", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.AddMissionRegistration")
    @ResponseWrapper(localName = "AddMissionRegistrationResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.AddMissionRegistrationResponse")
    @WebResult(name = "AddMissionRegistrationResult", targetNamespace = "http://tempuri.org/")
    public String addMissionRegistration(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "missionId", targetNamespace = "http://tempuri.org/")
        long missionId,
        @WebParam(name = "beginDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime
    );

    @WebMethod(operationName = "GetIoSources", action = "http://tempuri.org/GetIoSources")
    @RequestWrapper(localName = "GetIoSources", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetIoSources")
    @ResponseWrapper(localName = "GetIoSourcesResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetIoSourcesResponse")
    @WebResult(name = "GetIoSourcesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfString getIoSources()
;

    @WebMethod(operationName = "GetEmployeeFullNameFromLoginResult", action = "http://tempuri.org/GetEmployeeFullNameFromLoginResult")
    @RequestWrapper(localName = "GetEmployeeFullNameFromLoginResult", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetEmployeeFullNameFromLoginResult")
    @ResponseWrapper(localName = "GetEmployeeFullNameFromLoginResultResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetEmployeeFullNameFromLoginResultResponse")
    @WebResult(name = "GetEmployeeFullNameFromLoginResultResult", targetNamespace = "http://tempuri.org/")
    public String getEmployeeFullNameFromLoginResult(

        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password
    );

    @WebMethod(operationName = "GetUiRequestCartableIds", action = "http://tempuri.org/GetUiRequestCartableIds")
    @RequestWrapper(localName = "GetUiRequestCartableIds", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetUiRequestCartableIds")
    @ResponseWrapper(localName = "GetUiRequestCartableIdsResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetUiRequestCartableIdsResponse")
    @WebResult(name = "GetUiRequestCartableIdsResult", targetNamespace = "http://tempuri.org/")
    public UiRequestCartableIds getUiRequestCartableIds(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode
    );

    @WebMethod(operationName = "GetCalendarWorkDayTypesByEmployee", action = "http://tempuri.org/GetCalendarWorkDayTypesByEmployee")
    @RequestWrapper(localName = "GetCalendarWorkDayTypesByEmployee", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetCalendarWorkDayTypesByEmployee")
    @ResponseWrapper(localName = "GetCalendarWorkDayTypesByEmployeeResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetCalendarWorkDayTypesByEmployeeResponse")
    @WebResult(name = "GetCalendarWorkDayTypesByEmployeeResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfCalendarDayListDto getCalendarWorkDayTypesByEmployee(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        String toDate
    );

    @WebMethod(operationName = "GetAllEmployeesWithOrgId", action = "http://tempuri.org/GetAllEmployeesWithOrgId")
    @RequestWrapper(localName = "GetAllEmployeesWithOrgId", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllEmployeesWithOrgId")
    @ResponseWrapper(localName = "GetAllEmployeesWithOrgIdResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllEmployeesWithOrgIdResponse")
    @WebResult(name = "GetAllEmployeesWithOrgIdResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfEmployeeInfo getAllEmployeesWithOrgId()
;

    @WebMethod(operationName = "GetAllPeriodFunctionalityWinPayList", action = "http://tempuri.org/GetAllPeriodFunctionalityWinPayList")
    @RequestWrapper(localName = "GetAllPeriodFunctionalityWinPayList", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllPeriodFunctionalityWinPayList")
    @ResponseWrapper(localName = "GetAllPeriodFunctionalityWinPayListResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllPeriodFunctionalityWinPayListResponse")
    @WebResult(name = "GetAllPeriodFunctionalityWinPayListResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfPeriodCalculationInfo getAllPeriodFunctionalityWinPayList(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar date,
        @WebParam(name = "withVacation", targetNamespace = "http://tempuri.org/")
        boolean withVacation,
        @WebParam(name = "withSequenceWorkingDetails", targetNamespace = "http://tempuri.org/")
        boolean withSequenceWorkingDetails,
        @WebParam(name = "withSpecialExtraWork", targetNamespace = "http://tempuri.org/")
        boolean withSpecialExtraWork,
        @WebParam(name = "withVacationRemaining", targetNamespace = "http://tempuri.org/")
        boolean withVacationRemaining,
        @WebParam(name = "withSpecialAddSubVacation", targetNamespace = "http://tempuri.org/")
        boolean withSpecialAddSubVacation,
        @WebParam(name = "withMission", targetNamespace = "http://tempuri.org/")
        boolean withMission
    );

    @WebMethod(operationName = "GetOrganizationChartList", action = "http://tempuri.org/GetOrganizationChartList")
    @RequestWrapper(localName = "GetOrganizationChartList", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetOrganizationChartList")
    @ResponseWrapper(localName = "GetOrganizationChartListResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetOrganizationChartListResponse")
    @WebResult(name = "GetOrganizationChartListResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfString getOrganizationChartList(

        @WebParam(name = "regionId", targetNamespace = "http://tempuri.org/")
        long regionId
    );

    @WebMethod(operationName = "GetValidCardList", action = "http://tempuri.org/GetValidCardList")
    @RequestWrapper(localName = "GetValidCardList", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetValidCardList")
    @ResponseWrapper(localName = "GetValidCardListResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetValidCardListResponse")
    @WebResult(name = "GetValidCardListResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfString getValidCardList(

        @WebParam(name = "regionId", targetNamespace = "http://tempuri.org/")
        long regionId
    );

    @WebMethod(operationName = "GetAllVacationRegistrationsByDate", action = "http://tempuri.org/GetAllVacationRegistrationsByDate")
    @RequestWrapper(localName = "GetAllVacationRegistrationsByDate", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllVacationRegistrationsByDate")
    @ResponseWrapper(localName = "GetAllVacationRegistrationsByDateResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllVacationRegistrationsByDateResponse")
    @WebResult(name = "GetAllVacationRegistrationsByDateResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfVacationRegistrationDataModel getAllVacationRegistrationsByDate(

        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        String date
    );

    @WebMethod(operationName = "GetAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId", action = "http://tempuri.org/GetAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId")
    @RequestWrapper(localName = "GetAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId")
    @ResponseWrapper(localName = "GetAllSubsetOrganizationChartsWithEmployeesByCurrentOrgIdResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllSubsetOrganizationChartsWithEmployeesByCurrentOrgIdResponse")
    @WebResult(name = "GetAllSubsetOrganizationChartsWithEmployeesByCurrentOrgIdResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfOrganizationChartDataModel getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId(

        @WebParam(name = "currentOrganizationchartId", targetNamespace = "http://tempuri.org/")
        long currentOrganizationchartId
    );

    @WebMethod(operationName = "GetAllMissionRegistrationsByDate", action = "http://tempuri.org/GetAllMissionRegistrationsByDate")
    @RequestWrapper(localName = "GetAllMissionRegistrationsByDate", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllMissionRegistrationsByDate")
    @ResponseWrapper(localName = "GetAllMissionRegistrationsByDateResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllMissionRegistrationsByDateResponse")
    @WebResult(name = "GetAllMissionRegistrationsByDateResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfMissionRegistrationDataModel getAllMissionRegistrationsByDate(

        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        String date
    );

    @WebMethod(operationName = "GetIoRecordInDayByEmployeeCode", action = "http://tempuri.org/GetIoRecordInDayByEmployeeCode")
    @RequestWrapper(localName = "GetIoRecordInDayByEmployeeCode", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetIoRecordInDayByEmployeeCode")
    @ResponseWrapper(localName = "GetIoRecordInDayByEmployeeCodeResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetIoRecordInDayByEmployeeCodeResponse")
    @WebResult(name = "GetIoRecordInDayByEmployeeCodeResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfStaffIOs getIoRecordInDayByEmployeeCode(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "DayDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar dayDate
    );

    @WebMethod(operationName = "CheckTimeAttendanceSystemHasThirdPartyWebServicec", action = "http://tempuri.org/CheckTimeAttendanceSystemHasThirdPartyWebServicec")
    @RequestWrapper(localName = "CheckTimeAttendanceSystemHasThirdPartyWebServicec", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.CheckTimeAttendanceSystemHasThirdPartyWebServicec")
    @ResponseWrapper(localName = "CheckTimeAttendanceSystemHasThirdPartyWebServicecResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.CheckTimeAttendanceSystemHasThirdPartyWebServicecResponse")
    @WebResult(name = "CheckTimeAttendanceSystemHasThirdPartyWebServicecResult", targetNamespace = "http://tempuri.org/")
    public boolean checkTimeAttendanceSystemHasThirdPartyWebServicec()
;

    @WebMethod(operationName = "GetAllOrganizationChartList", action = "http://tempuri.org/GetAllOrganizationChartList")
    @RequestWrapper(localName = "GetAllOrganizationChartList", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllOrganizationChartList")
    @ResponseWrapper(localName = "GetAllOrganizationChartListResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllOrganizationChartListResponse")
    @WebResult(name = "GetAllOrganizationChartListResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfOrganizationChartDataModel getAllOrganizationChartList()
;

    @WebMethod(operationName = "GetAllEmployees", action = "http://tempuri.org/GetAllEmployees")
    @RequestWrapper(localName = "GetAllEmployees", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllEmployees")
    @ResponseWrapper(localName = "GetAllEmployeesResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllEmployeesResponse")
    @WebResult(name = "GetAllEmployeesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfEmployeeDataModel getAllEmployees()
;

    @WebMethod(operationName = "GetRemainUiEmployeeVacationTypeRepositoryList", action = "http://tempuri.org/GetRemainUiEmployeeVacationTypeRepositoryList")
    @RequestWrapper(localName = "GetRemainUiEmployeeVacationTypeRepositoryList", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetRemainUiEmployeeVacationTypeRepositoryList")
    @ResponseWrapper(localName = "GetRemainUiEmployeeVacationTypeRepositoryListResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetRemainUiEmployeeVacationTypeRepositoryListResponse")
    @WebResult(name = "GetRemainUiEmployeeVacationTypeRepositoryListResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfString getRemainUiEmployeeVacationTypeRepositoryList(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "CurrentWorkingYear", targetNamespace = "http://tempuri.org/")
        long currentWorkingYear
    );

    @WebMethod(operationName = "GetAllSpecialExtraWorksByPeriodId", action = "http://tempuri.org/GetAllSpecialExtraWorksByPeriodId")
    @RequestWrapper(localName = "GetAllSpecialExtraWorksByPeriodId", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllSpecialExtraWorksByPeriodId")
    @ResponseWrapper(localName = "GetAllSpecialExtraWorksByPeriodIdResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllSpecialExtraWorksByPeriodIdResponse")
    @WebResult(name = "GetAllSpecialExtraWorksByPeriodIdResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfSpecialExtraWorkDataModel getAllSpecialExtraWorksByPeriodId(

        @WebParam(name = "periodId", targetNamespace = "http://tempuri.org/")
        long periodId
    );

    @WebMethod(operationName = "GetEmployeeCodeByKeyNumber", action = "http://tempuri.org/GetEmployeeCodeByKeyNumber")
    @RequestWrapper(localName = "GetEmployeeCodeByKeyNumber", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetEmployeeCodeByKeyNumber")
    @ResponseWrapper(localName = "GetEmployeeCodeByKeyNumberResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetEmployeeCodeByKeyNumberResponse")
    @WebResult(name = "GetEmployeeCodeByKeyNumberResult", targetNamespace = "http://tempuri.org/")
    public String getEmployeeCodeByKeyNumber(

        @WebParam(name = "keyNumber", targetNamespace = "http://tempuri.org/")
        String keyNumber,
        @WebParam(name = "gregorianDate", targetNamespace = "http://tempuri.org/")
        String gregorianDate,
        @WebParam(name = "shamsiDate", targetNamespace = "http://tempuri.org/")
        String shamsiDate,
        @WebParam(name = "systemType", targetNamespace = "http://tempuri.org/")
        SystemModuleType systemType,
        @WebParam(name = "deviceModuleType", targetNamespace = "http://tempuri.org/")
        UiDeviceModuleType deviceModuleType
    );

    @WebMethod(operationName = "GetIsExitOverTimeList", action = "http://tempuri.org/GetIsExitOverTimeList")
    @RequestWrapper(localName = "GetIsExitOverTimeList", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetIsExitOverTimeList")
    @ResponseWrapper(localName = "GetIsExitOverTimeListResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetIsExitOverTimeListResponse")
    @WebResult(name = "GetIsExitOverTimeListResult", targetNamespace = "http://tempuri.org/")
    public boolean getIsExitOverTimeList(

        @WebParam(name = "perno", targetNamespace = "http://tempuri.org/")
        String perno,
        @WebParam(name = "time", targetNamespace = "http://tempuri.org/")
        String time,
        @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDate
    );

    @WebMethod(operationName = "GetOrganizationChartIdByEmployee", action = "http://tempuri.org/GetOrganizationChartIdByEmployee")
    @RequestWrapper(localName = "GetOrganizationChartIdByEmployee", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetOrganizationChartIdByEmployee")
    @ResponseWrapper(localName = "GetOrganizationChartIdByEmployeeResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetOrganizationChartIdByEmployeeResponse")
    @WebResult(name = "GetOrganizationChartIdByEmployeeResult", targetNamespace = "http://tempuri.org/")
    public long getOrganizationChartIdByEmployee(

        @WebParam(name = "regionId", targetNamespace = "http://tempuri.org/")
        long regionId,
        @WebParam(name = "employeeId", targetNamespace = "http://tempuri.org/")
        long employeeId
    );

    @WebMethod(operationName = "GetDayCalculationInfo", action = "http://tempuri.org/GetDayCalculationInfo")
    @RequestWrapper(localName = "GetDayCalculationInfo", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetDayCalculationInfo")
    @ResponseWrapper(localName = "GetDayCalculationInfoResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetDayCalculationInfoResponse")
    public void getDayCalculationInfo(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetListOfEmployeeEvents", action = "http://tempuri.org/GetListOfEmployeeEvents")
    @RequestWrapper(localName = "GetListOfEmployeeEvents", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetListOfEmployeeEvents")
    @ResponseWrapper(localName = "GetListOfEmployeeEventsResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetListOfEmployeeEventsResponse")
    @WebResult(name = "GetListOfEmployeeEventsResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfEmployeeDataModel getListOfEmployeeEvents(

        @WebParam(name = "employeeEvent", targetNamespace = "http://tempuri.org/")
        EmployeeEventType employeeEvent
    );

    @WebMethod(operationName = "AddVacationRegistration", action = "http://tempuri.org/AddVacationRegistration")
    @RequestWrapper(localName = "AddVacationRegistration", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.AddVacationRegistration")
    @ResponseWrapper(localName = "AddVacationRegistrationResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.AddVacationRegistrationResponse")
    @WebResult(name = "AddVacationRegistrationResult", targetNamespace = "http://tempuri.org/")
    public String addVacationRegistration(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "vacationId", targetNamespace = "http://tempuri.org/")
        long vacationId,
        @WebParam(name = "beginDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime
    );

    @WebMethod(operationName = "GetAllCurrentlyEmployees", action = "http://tempuri.org/GetAllCurrentlyEmployees")
    @RequestWrapper(localName = "GetAllCurrentlyEmployees", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllCurrentlyEmployees")
    @ResponseWrapper(localName = "GetAllCurrentlyEmployeesResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllCurrentlyEmployeesResponse")
    @WebResult(name = "GetAllCurrentlyEmployeesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfEmployeeDataModel getAllCurrentlyEmployees()
;

    @WebMethod(operationName = "GetAllEmployeesOfOneOrganizationChartWithAllSubsets", action = "http://tempuri.org/GetAllEmployeesOfOneOrganizationChartWithAllSubsets")
    @RequestWrapper(localName = "GetAllEmployeesOfOneOrganizationChartWithAllSubsets", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllEmployeesOfOneOrganizationChartWithAllSubsets")
    @ResponseWrapper(localName = "GetAllEmployeesOfOneOrganizationChartWithAllSubsetsResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllEmployeesOfOneOrganizationChartWithAllSubsetsResponse")
    @WebResult(name = "GetAllEmployeesOfOneOrganizationChartWithAllSubsetsResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfEmployeeDataModel getAllEmployeesOfOneOrganizationChartWithAllSubsets(

        @WebParam(name = "currentOrganizationchartId", targetNamespace = "http://tempuri.org/")
        long currentOrganizationchartId
    );

    @WebMethod(operationName = "GetIORecordAfterId", action = "http://tempuri.org/GetIORecordAfterId")
    @RequestWrapper(localName = "GetIORecordAfterId", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetIORecordAfterId")
    @ResponseWrapper(localName = "GetIORecordAfterIdResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetIORecordAfterIdResponse")
    @WebResult(name = "GetIORecordAfterIdResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfIoRecordDataModel getIORecordAfterId(

        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        long id
    );

    @WebMethod(operationName = "IsPresent", action = "http://tempuri.org/IsPresent")
    @RequestWrapper(localName = "IsPresent", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.IsPresent")
    @ResponseWrapper(localName = "IsPresentResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.IsPresentResponse")
    @WebResult(name = "IsPresentResult", targetNamespace = "http://tempuri.org/")
    public boolean isPresent(

        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        long id,
        @WebParam(name = "dateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar dateTime
    );

    @WebMethod(operationName = "GetDevicePersons", action = "http://tempuri.org/GetDevicePersons")
    @RequestWrapper(localName = "GetDevicePersons", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetDevicePersons")
    @ResponseWrapper(localName = "GetDevicePersonsResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetDevicePersonsResponse")
    @WebResult(name = "GetDevicePersonsResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfDevicePerson getDevicePersons(

        @WebParam(name = "deviceModuleType", targetNamespace = "http://tempuri.org/")
        java.util.List<String> deviceModuleType
    );

    @WebMethod(operationName = "GetAllIoRecordsByDate", action = "http://tempuri.org/GetAllIoRecordsByDate")
    @RequestWrapper(localName = "GetAllIoRecordsByDate", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllIoRecordsByDate")
    @ResponseWrapper(localName = "GetAllIoRecordsByDateResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllIoRecordsByDateResponse")
    @WebResult(name = "GetAllIoRecordsByDateResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfIoRecordDataModel getAllIoRecordsByDate(

        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        String date
    );

    @WebMethod(operationName = "GetUiRequestCartableCount", action = "http://tempuri.org/GetUiRequestCartableCount")
    @RequestWrapper(localName = "GetUiRequestCartableCount", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetUiRequestCartableCount")
    @ResponseWrapper(localName = "GetUiRequestCartableCountResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetUiRequestCartableCountResponse")
    @WebResult(name = "GetUiRequestCartableCountResult", targetNamespace = "http://tempuri.org/")
    public String getUiRequestCartableCount(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode
    );

    @WebMethod(operationName = "GetRemainUiEmployeeVacationTypeRepository", action = "http://tempuri.org/GetRemainUiEmployeeVacationTypeRepository")
    @RequestWrapper(localName = "GetRemainUiEmployeeVacationTypeRepository", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetRemainUiEmployeeVacationTypeRepository")
    @ResponseWrapper(localName = "GetRemainUiEmployeeVacationTypeRepositoryResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetRemainUiEmployeeVacationTypeRepositoryResponse")
    @WebResult(name = "GetRemainUiEmployeeVacationTypeRepositoryResult", targetNamespace = "http://tempuri.org/")
    public String getRemainUiEmployeeVacationTypeRepository(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "vacationtypeId", targetNamespace = "http://tempuri.org/")
        long vacationtypeId
    );

    @WebMethod(operationName = "GetAllValidEmployeeRange", action = "http://tempuri.org/GetAllValidEmployeeRange")
    @RequestWrapper(localName = "GetAllValidEmployeeRange", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllValidEmployeeRange")
    @ResponseWrapper(localName = "GetAllValidEmployeeRangeResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetAllValidEmployeeRangeResponse")
    @WebResult(name = "GetAllValidEmployeeRangeResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfValidEmployeeRange getAllValidEmployeeRange(

        @WebParam(name = "dateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar dateTime,
        @WebParam(name = "requestState", targetNamespace = "http://tempuri.org/")
        int requestState
    );

    @WebMethod(operationName = "GetIORecordPerDateRange", action = "http://tempuri.org/GetIORecordPerDateRange")
    @RequestWrapper(localName = "GetIORecordPerDateRange", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetIORecordPerDateRange")
    @ResponseWrapper(localName = "GetIORecordPerDateRangeResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetIORecordPerDateRangeResponse")
    @WebResult(name = "GetIORecordPerDateRangeResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfIoRecordDataModel getIORecordPerDateRange(

        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        String toDate
    );

    @WebMethod(operationName = "GetCalendarWorkDayTypes", action = "http://tempuri.org/GetCalendarWorkDayTypes")
    @RequestWrapper(localName = "GetCalendarWorkDayTypes", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetCalendarWorkDayTypes")
    @ResponseWrapper(localName = "GetCalendarWorkDayTypesResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetCalendarWorkDayTypesResponse")
    @WebResult(name = "GetCalendarWorkDayTypesResult", targetNamespace = "http://tempuri.org/")
    public ArrayOfCalendarDayListDto getCalendarWorkDayTypes(

        @WebParam(name = "calendarName", targetNamespace = "http://tempuri.org/")
        String calendarName,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        String toDate
    );

    @WebMethod(operationName = "AddMissionRegistrationEx", action = "http://tempuri.org/AddMissionRegistrationEx")
    @RequestWrapper(localName = "AddMissionRegistrationEx", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.AddMissionRegistrationEx")
    @ResponseWrapper(localName = "AddMissionRegistrationExResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.AddMissionRegistrationExResponse")
    @WebResult(name = "AddMissionRegistrationExResult", targetNamespace = "http://tempuri.org/")
    public String addMissionRegistrationEx(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "confirmEmployeeCode", targetNamespace = "http://tempuri.org/")
        String confirmEmployeeCode,
        @WebParam(name = "missionId", targetNamespace = "http://tempuri.org/")
        long missionId,
        @WebParam(name = "beginDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime,
        @WebParam(name = "missionLocationName", targetNamespace = "http://tempuri.org/")
        String missionLocationName
    );

    @WebMethod(operationName = "AddVacationRegistrationPermission", action = "http://tempuri.org/AddVacationRegistrationPermission")
    @RequestWrapper(localName = "AddVacationRegistrationPermission", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.AddVacationRegistrationPermission")
    @ResponseWrapper(localName = "AddVacationRegistrationPermissionResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.AddVacationRegistrationPermissionResponse")
    @WebResult(name = "AddVacationRegistrationPermissionResult", targetNamespace = "http://tempuri.org/")
    public String addVacationRegistrationPermission(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "vacationId", targetNamespace = "http://tempuri.org/")
        long vacationId,
        @WebParam(name = "beginDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime,
        @WebParam(name = "vacationRequestReason", targetNamespace = "http://tempuri.org/")
        String vacationRequestReason,
        @WebParam(name = "description", targetNamespace = "http://tempuri.org/")
        String description
    );

    @WebMethod(operationName = "PersistIoRecrd", action = "http://tempuri.org/PersistIoRecrd")
    @RequestWrapper(localName = "PersistIoRecrd", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.PersistIoRecrd")
    @ResponseWrapper(localName = "PersistIoRecrdResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.PersistIoRecrdResponse")
    @WebResult(name = "PersistIoRecrdResult", targetNamespace = "http://tempuri.org/")
    public boolean persistIoRecrd(

        @WebParam(name = "keyNumber", targetNamespace = "http://tempuri.org/")
        String keyNumber,
        @WebParam(name = "ioDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar ioDateTime,
        @WebParam(name = "deviceModuleType", targetNamespace = "http://tempuri.org/")
        long deviceModuleType,
        @WebParam(name = "hadwareCode", targetNamespace = "http://tempuri.org/")
        long hadwareCode
    );

    @WebMethod(operationName = "GetTimeAttendancePcCheckByEmployeeCode", action = "http://tempuri.org/GetTimeAttendancePcCheckByEmployeeCode")
    @RequestWrapper(localName = "GetTimeAttendancePcCheckByEmployeeCode", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetTimeAttendancePcCheckByEmployeeCode")
    @ResponseWrapper(localName = "GetTimeAttendancePcCheckByEmployeeCodeResponse", targetNamespace = "http://tempuri.org/", className = "edu.imi.ir.eduimiws.models.wsdl.attendance.GetTimeAttendancePcCheckByEmployeeCodeResponse")
    public void getTimeAttendancePcCheckByEmployeeCode(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        String employeeCode,
        @WebParam(name = "dateTime", targetNamespace = "http://tempuri.org/")
        String dateTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetTimeAttendancePcCheckByEmployeeCodeResult", targetNamespace = "http://tempuri.org/")
        jakarta.xml.ws.Holder<Boolean> getTimeAttendancePcCheckByEmployeeCodeResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "reason", targetNamespace = "http://tempuri.org/")
        jakarta.xml.ws.Holder<String> reason
    );
}
