//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.30 at 02:03:28 PM GMT+03:30 
//


package edu.imi.ir.eduimiws.models.wsdl.sabtahval;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.imi.ir.eduimiws.models.sabtahval package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.imi.ir.eduimiws.models.sabtahval
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EstelamRIResponse }
     * 
     */
    public EstelamRIResponse createEstelamRIResponse() {
        return new EstelamRIResponse();
    }

    /**
     * Create an instance of {@link EstelamRIResponse.Request }
     * 
     */
    public EstelamRIResponse.Request createEstelamRIResponseRequest() {
        return new EstelamRIResponse.Request();
    }

    /**
     * Create an instance of {@link GetImageSmartResponse }
     * 
     */
    public GetImageSmartResponse createGetImageSmartResponse() {
        return new GetImageSmartResponse();
    }

    /**
     * Create an instance of {@link ImageResult }
     * 
     */
    public ImageResult createImageResult() {
        return new ImageResult();
    }

    /**
     * Create an instance of {@link Estelam11Request }
     * 
     */
    public Estelam11Request createEstelam11Request() {
        return new Estelam11Request();
    }

    /**
     * Create an instance of {@link GetImage6Response }
     * 
     */
    public GetImage6Response createGetImage6Response() {
        return new GetImage6Response();
    }

    /**
     * Create an instance of {@link Image6Result }
     * 
     */
    public Image6Result createImage6Result() {
        return new Image6Result();
    }

    /**
     * Create an instance of {@link GetEstelam12Response }
     * 
     */
    public GetEstelam12Response createGetEstelam12Response() {
        return new GetEstelam12Response();
    }

    /**
     * Create an instance of {@link EstelamResult12 }
     * 
     */
    public EstelamResult12 createEstelamResult12() {
        return new EstelamResult12();
    }

    /**
     * Create an instance of {@link GetVersionResponse }
     * 
     */
    public GetVersionResponse createGetVersionResponse() {
        return new GetVersionResponse();
    }

    /**
     * Create an instance of {@link GetEstelam8C }
     * 
     */
    public GetEstelam8C createGetEstelam8C() {
        return new GetEstelam8C();
    }

    /**
     * Create an instance of {@link PersonInfo3F }
     * 
     */
    public PersonInfo3F createPersonInfo3F() {
        return new PersonInfo3F();
    }

    /**
     * Create an instance of {@link SenderInfo3F }
     * 
     */
    public SenderInfo3F createSenderInfo3F() {
        return new SenderInfo3F();
    }

    /**
     * Create an instance of {@link GetEstelam3T }
     * 
     */
    public GetEstelam3T createGetEstelam3T() {
        return new GetEstelam3T();
    }

    /**
     * Create an instance of {@link Estelam3TRequest }
     * 
     */
    public Estelam3TRequest createEstelam3TRequest() {
        return new Estelam3TRequest();
    }

    /**
     * Create an instance of {@link GetEstelam16Response }
     * 
     */
    public GetEstelam16Response createGetEstelam16Response() {
        return new GetEstelam16Response();
    }

    /**
     * Create an instance of {@link Estelam16Result }
     * 
     */
    public Estelam16Result createEstelam16Result() {
        return new Estelam16Result();
    }

    /**
     * Create an instance of {@link GetImageSmart }
     * 
     */
    public GetImageSmart createGetImageSmart() {
        return new GetImageSmart();
    }

    /**
     * Create an instance of {@link GetEstelam11Response }
     * 
     */
    public GetEstelam11Response createGetEstelam11Response() {
        return new GetEstelam11Response();
    }

    /**
     * Create an instance of {@link EstelamResult11 }
     * 
     */
    public EstelamResult11 createEstelamResult11() {
        return new EstelamResult11();
    }

    /**
     * Create an instance of {@link GetEstelam15Response }
     * 
     */
    public GetEstelam15Response createGetEstelam15Response() {
        return new GetEstelam15Response();
    }

    /**
     * Create an instance of {@link EstelamResult15 }
     * 
     */
    public EstelamResult15 createEstelamResult15() {
        return new EstelamResult15();
    }

    /**
     * Create an instance of {@link GetEstelam7 }
     * 
     */
    public GetEstelam7 createGetEstelam7() {
        return new GetEstelam7();
    }

    /**
     * Create an instance of {@link GetEstelam2SC }
     * 
     */
    public GetEstelam2SC createGetEstelam2SC() {
        return new GetEstelam2SC();
    }

    /**
     * Create an instance of {@link PersonInfo }
     * 
     */
    public PersonInfo createPersonInfo() {
        return new PersonInfo();
    }

    /**
     * Create an instance of {@link GetImage4Response }
     * 
     */
    public GetImage4Response createGetImage4Response() {
        return new GetImage4Response();
    }

    /**
     * Create an instance of {@link GetEstelam13Response }
     * 
     */
    public GetEstelam13Response createGetEstelam13Response() {
        return new GetEstelam13Response();
    }

    /**
     * Create an instance of {@link EstelamResult13 }
     * 
     */
    public EstelamResult13 createEstelamResult13() {
        return new EstelamResult13();
    }

    /**
     * Create an instance of {@link GetEstelam4 }
     * 
     */
    public GetEstelam4 createGetEstelam4() {
        return new GetEstelam4();
    }

    /**
     * Create an instance of {@link GetEstelam3 }
     * 
     */
    public GetEstelam3 createGetEstelam3() {
        return new GetEstelam3();
    }

    /**
     * Create an instance of {@link GetEstelamRIResponse }
     * 
     */
    public GetEstelamRIResponse createGetEstelamRIResponse() {
        return new GetEstelamRIResponse();
    }

    /**
     * Create an instance of {@link GetEstelam5 }
     * 
     */
    public GetEstelam5 createGetEstelam5() {
        return new GetEstelam5();
    }

    /**
     * Create an instance of {@link GetEstelam10Response }
     * 
     */
    public GetEstelam10Response createGetEstelam10Response() {
        return new GetEstelam10Response();
    }

    /**
     * Create an instance of {@link EstelamResult10 }
     * 
     */
    public EstelamResult10 createEstelamResult10() {
        return new EstelamResult10();
    }

    /**
     * Create an instance of {@link GetImage2Response }
     * 
     */
    public GetImage2Response createGetImage2Response() {
        return new GetImage2Response();
    }

    /**
     * Create an instance of {@link GetEstelam7C }
     * 
     */
    public GetEstelam7C createGetEstelam7C() {
        return new GetEstelam7C();
    }

    /**
     * Create an instance of {@link EstelamRequest }
     * 
     */
    public EstelamRequest createEstelamRequest() {
        return new EstelamRequest();
    }

    /**
     * Create an instance of {@link GetEstelam14Response }
     * 
     */
    public GetEstelam14Response createGetEstelam14Response() {
        return new GetEstelam14Response();
    }

    /**
     * Create an instance of {@link EstelamResult14 }
     * 
     */
    public EstelamResult14 createEstelamResult14() {
        return new EstelamResult14();
    }

    /**
     * Create an instance of {@link GetEstelamRI }
     * 
     */
    public GetEstelamRI createGetEstelamRI() {
        return new GetEstelamRI();
    }

    /**
     * Create an instance of {@link GetEstelam2SCResponse }
     * 
     */
    public GetEstelam2SCResponse createGetEstelam2SCResponse() {
        return new GetEstelam2SCResponse();
    }

    /**
     * Create an instance of {@link EstelamResult }
     * 
     */
    public EstelamResult createEstelamResult() {
        return new EstelamResult();
    }

    /**
     * Create an instance of {@link GetEstelam3CResponse }
     * 
     */
    public GetEstelam3CResponse createGetEstelam3CResponse() {
        return new GetEstelam3CResponse();
    }

    /**
     * Create an instance of {@link EstelamResultC }
     * 
     */
    public EstelamResultC createEstelamResultC() {
        return new EstelamResultC();
    }

    /**
     * Create an instance of {@link GetEstelam3Response }
     * 
     */
    public GetEstelam3Response createGetEstelam3Response() {
        return new GetEstelam3Response();
    }

    /**
     * Create an instance of {@link EstelamResult3 }
     * 
     */
    public EstelamResult3 createEstelamResult3() {
        return new EstelamResult3();
    }

    /**
     * Create an instance of {@link GetEstelam3C }
     * 
     */
    public GetEstelam3C createGetEstelam3C() {
        return new GetEstelam3C();
    }

    /**
     * Create an instance of {@link GetEstelam2 }
     * 
     */
    public GetEstelam2 createGetEstelam2() {
        return new GetEstelam2();
    }

    /**
     * Create an instance of {@link GetEstelam7CResponse }
     * 
     */
    public GetEstelam7CResponse createGetEstelam7CResponse() {
        return new GetEstelam7CResponse();
    }

    /**
     * Create an instance of {@link EstelamResult7C }
     * 
     */
    public EstelamResult7C createEstelamResult7C() {
        return new EstelamResult7C();
    }

    /**
     * Create an instance of {@link Estelam3TPersonInfoResult }
     * 
     */
    public Estelam3TPersonInfoResult createEstelam3TPersonInfoResult() {
        return new Estelam3TPersonInfoResult();
    }

    /**
     * Create an instance of {@link GetEstelam19Response }
     * 
     */
    public GetEstelam19Response createGetEstelam19Response() {
        return new GetEstelam19Response();
    }

    /**
     * Create an instance of {@link Estelam19Result }
     * 
     */
    public Estelam19Result createEstelam19Result() {
        return new Estelam19Result();
    }

    /**
     * Create an instance of {@link Image6Request }
     * 
     */
    public Image6Request createImage6Request() {
        return new Image6Request();
    }

    /**
     * Create an instance of {@link GetEstelam20Response }
     * 
     */
    public GetEstelam20Response createGetEstelam20Response() {
        return new GetEstelam20Response();
    }

    /**
     * Create an instance of {@link Estelam20Result }
     * 
     */
    public Estelam20Result createEstelam20Result() {
        return new Estelam20Result();
    }

    /**
     * Create an instance of {@link Exception3F }
     * 
     */
    public Exception3F createException3F() {
        return new Exception3F();
    }

    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

    /**
     * Create an instance of {@link GetEstelam17Response }
     * 
     */
    public GetEstelam17Response createGetEstelam17Response() {
        return new GetEstelam17Response();
    }

    /**
     * Create an instance of {@link EstelamResult17 }
     * 
     */
    public EstelamResult17 createEstelamResult17() {
        return new EstelamResult17();
    }

    /**
     * Create an instance of {@link EstelamResult3T }
     * 
     */
    public EstelamResult3T createEstelamResult3T() {
        return new EstelamResult3T();
    }

    /**
     * Create an instance of {@link TrackingInfo }
     * 
     */
    public TrackingInfo createTrackingInfo() {
        return new TrackingInfo();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link GetEstelam18Response }
     * 
     */
    public GetEstelam18Response createGetEstelam18Response() {
        return new GetEstelam18Response();
    }

    /**
     * Create an instance of {@link Estelam18Result }
     * 
     */
    public Estelam18Result createEstelam18Result() {
        return new Estelam18Result();
    }

    /**
     * Create an instance of {@link GetEstelam8CResponse }
     * 
     */
    public GetEstelam8CResponse createGetEstelam8CResponse() {
        return new GetEstelam8CResponse();
    }

    /**
     * Create an instance of {@link EstelamResult6C }
     * 
     */
    public EstelamResult6C createEstelamResult6C() {
        return new EstelamResult6C();
    }

    /**
     * Create an instance of {@link GetVersion }
     * 
     */
    public GetVersion createGetVersion() {
        return new GetVersion();
    }

    /**
     * Create an instance of {@link GetEstelam20 }
     * 
     */
    public GetEstelam20 createGetEstelam20() {
        return new GetEstelam20();
    }

    /**
     * Create an instance of {@link Estelam20Request }
     * 
     */
    public Estelam20Request createEstelam20Request() {
        return new Estelam20Request();
    }

    /**
     * Create an instance of {@link GetEstelam3SC }
     * 
     */
    public GetEstelam3SC createGetEstelam3SC() {
        return new GetEstelam3SC();
    }

    /**
     * Create an instance of {@link GetEstelam6CResponse }
     * 
     */
    public GetEstelam6CResponse createGetEstelam6CResponse() {
        return new GetEstelam6CResponse();
    }

    /**
     * Create an instance of {@link GetEstelam3TResponse }
     * 
     */
    public GetEstelam3TResponse createGetEstelam3TResponse() {
        return new GetEstelam3TResponse();
    }

    /**
     * Create an instance of {@link GetEstelam6C }
     * 
     */
    public GetEstelam6C createGetEstelam6C() {
        return new GetEstelam6C();
    }

    /**
     * Create an instance of {@link GetEstelam8RIResponse }
     * 
     */
    public GetEstelam8RIResponse createGetEstelam8RIResponse() {
        return new GetEstelam8RIResponse();
    }

    /**
     * Create an instance of {@link SenderResponseInfo }
     * 
     */
    public SenderResponseInfo createSenderResponseInfo() {
        return new SenderResponseInfo();
    }

    /**
     * Create an instance of {@link GetEstelam4Response }
     * 
     */
    public GetEstelam4Response createGetEstelam4Response() {
        return new GetEstelam4Response();
    }

    /**
     * Create an instance of {@link EstelamResult4 }
     * 
     */
    public EstelamResult4 createEstelamResult4() {
        return new EstelamResult4();
    }

    /**
     * Create an instance of {@link GetEstelam7Response }
     * 
     */
    public GetEstelam7Response createGetEstelam7Response() {
        return new GetEstelam7Response();
    }

    /**
     * Create an instance of {@link EstelamResult7 }
     * 
     */
    public EstelamResult7 createEstelamResult7() {
        return new EstelamResult7();
    }

    /**
     * Create an instance of {@link GetImage4 }
     * 
     */
    public GetImage4 createGetImage4() {
        return new GetImage4();
    }

    /**
     * Create an instance of {@link GetImage2 }
     * 
     */
    public GetImage2 createGetImage2() {
        return new GetImage2();
    }

    /**
     * Create an instance of {@link GetEstelam15 }
     * 
     */
    public GetEstelam15 createGetEstelam15() {
        return new GetEstelam15();
    }

    /**
     * Create an instance of {@link Estelam15Request }
     * 
     */
    public Estelam15Request createEstelam15Request() {
        return new Estelam15Request();
    }

    /**
     * Create an instance of {@link GetEstelam14 }
     * 
     */
    public GetEstelam14 createGetEstelam14() {
        return new GetEstelam14();
    }

    /**
     * Create an instance of {@link Estelam14Request }
     * 
     */
    public Estelam14Request createEstelam14Request() {
        return new Estelam14Request();
    }

    /**
     * Create an instance of {@link GetEstelam13 }
     * 
     */
    public GetEstelam13 createGetEstelam13() {
        return new GetEstelam13();
    }

    /**
     * Create an instance of {@link Estelam13Request }
     * 
     */
    public Estelam13Request createEstelam13Request() {
        return new Estelam13Request();
    }

    /**
     * Create an instance of {@link GetEstelam3SCResponse }
     * 
     */
    public GetEstelam3SCResponse createGetEstelam3SCResponse() {
        return new GetEstelam3SCResponse();
    }

    /**
     * Create an instance of {@link GetEstelam5Response }
     * 
     */
    public GetEstelam5Response createGetEstelam5Response() {
        return new GetEstelam5Response();
    }

    /**
     * Create an instance of {@link EstelamResult5 }
     * 
     */
    public EstelamResult5 createEstelamResult5() {
        return new EstelamResult5();
    }

    /**
     * Create an instance of {@link GetEstelam12 }
     * 
     */
    public GetEstelam12 createGetEstelam12() {
        return new GetEstelam12();
    }

    /**
     * Create an instance of {@link Estelam12Request }
     * 
     */
    public Estelam12Request createEstelam12Request() {
        return new Estelam12Request();
    }

    /**
     * Create an instance of {@link GetEstelam11 }
     * 
     */
    public GetEstelam11 createGetEstelam11() {
        return new GetEstelam11();
    }

    /**
     * Create an instance of {@link GetEstelam10 }
     * 
     */
    public GetEstelam10 createGetEstelam10() {
        return new GetEstelam10();
    }

    /**
     * Create an instance of {@link Estelam10PersonInfo }
     * 
     */
    public Estelam10PersonInfo createEstelam10PersonInfo() {
        return new Estelam10PersonInfo();
    }

    /**
     * Create an instance of {@link GetImage6 }
     * 
     */
    public GetImage6 createGetImage6() {
        return new GetImage6();
    }

    /**
     * Create an instance of {@link GetEstelam8RI }
     * 
     */
    public GetEstelam8RI createGetEstelam8RI() {
        return new GetEstelam8RI();
    }

    /**
     * Create an instance of {@link GetEstelam2Response }
     * 
     */
    public GetEstelam2Response createGetEstelam2Response() {
        return new GetEstelam2Response();
    }

    /**
     * Create an instance of {@link GetEstelam19 }
     * 
     */
    public GetEstelam19 createGetEstelam19() {
        return new GetEstelam19();
    }

    /**
     * Create an instance of {@link Estelam19Request }
     * 
     */
    public Estelam19Request createEstelam19Request() {
        return new Estelam19Request();
    }

    /**
     * Create an instance of {@link GetEstelam18 }
     * 
     */
    public GetEstelam18 createGetEstelam18() {
        return new GetEstelam18();
    }

    /**
     * Create an instance of {@link Estelam18Request }
     * 
     */
    public Estelam18Request createEstelam18Request() {
        return new Estelam18Request();
    }

    /**
     * Create an instance of {@link GetEstelam17 }
     * 
     */
    public GetEstelam17 createGetEstelam17() {
        return new GetEstelam17();
    }

    /**
     * Create an instance of {@link Estelam17Request }
     * 
     */
    public Estelam17Request createEstelam17Request() {
        return new Estelam17Request();
    }

    /**
     * Create an instance of {@link GetEstelam16 }
     * 
     */
    public GetEstelam16 createGetEstelam16() {
        return new GetEstelam16();
    }

    /**
     * Create an instance of {@link Estelam16Request }
     * 
     */
    public Estelam16Request createEstelam16Request() {
        return new Estelam16Request();
    }

    /**
     * Create an instance of {@link UnsupportedEncodingException }
     * 
     */
    public UnsupportedEncodingException createUnsupportedEncodingException() {
        return new UnsupportedEncodingException();
    }

    /**
     * Create an instance of {@link EstelamResult7CB }
     * 
     */
    public EstelamResult7CB createEstelamResult7CB() {
        return new EstelamResult7CB();
    }

    /**
     * Create an instance of {@link ActionMessages }
     * 
     */
    public ActionMessages createActionMessages() {
        return new ActionMessages();
    }

    /**
     * Create an instance of {@link ImageResult3F }
     * 
     */
    public ImageResult3F createImageResult3F() {
        return new ImageResult3F();
    }

    /**
     * Create an instance of {@link EstelamResult6 }
     * 
     */
    public EstelamResult6 createEstelamResult6() {
        return new EstelamResult6();
    }

    /**
     * Create an instance of {@link EstelamRIResponse.Request.Entry }
     * 
     */
    public EstelamRIResponse.Request.Entry createEstelamRIResponseRequestEntry() {
        return new EstelamRIResponse.Request.Entry();
    }

}
