package edu.imi.ir.eduimiws.models.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-01-08T17:24:18.796+03:30
 * Generated source version: 3.6.5
 *
 */
@WebService(targetNamespace = "http://interfaces.core.sw.bps.com/", name = "IPaymentGateway")
@XmlSeeAlso({ObjectFactory.class})
public interface IPaymentGateway {

    @WebMethod
    @RequestWrapper(localName = "bpRefundRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpRefundRequest")
    @ResponseWrapper(localName = "bpRefundRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpRefundRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpRefundRequest(

        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "saleOrderId", targetNamespace = "")
        long saleOrderId,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        long saleReferenceId,
        @WebParam(name = "refundAmount", targetNamespace = "")
        long refundAmount
    );

    @WebMethod
    @RequestWrapper(localName = "bpSaleReferenceIdRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpSaleReferenceIdRequest")
    @ResponseWrapper(localName = "bpSaleReferenceIdRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpSaleReferenceIdRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpSaleReferenceIdRequest(

        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "saleOrderId", targetNamespace = "")
        long saleOrderId
    );

    @WebMethod
    @RequestWrapper(localName = "bpRefundToPANRequestV2", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpRefundToPANRequestV2")
    @ResponseWrapper(localName = "bpRefundToPANRequestV2Response", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpRefundToPANRequestV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpRefundToPANRequestV2(

        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "pan", targetNamespace = "")
        java.lang.Long pan,
        @WebParam(name = "amount", targetNamespace = "")
        long amount,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        java.lang.Long saleReferenceId,
        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "mobileNo", targetNamespace = "")
        java.lang.String mobileNo
    );

    @WebMethod
    @RequestWrapper(localName = "bpDynamicPayRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpDynamicPayRequest")
    @ResponseWrapper(localName = "bpDynamicPayRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpDynamicPayRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpDynamicPayRequest(

        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "amount", targetNamespace = "")
        long amount,
        @WebParam(name = "localDate", targetNamespace = "")
        java.lang.String localDate,
        @WebParam(name = "localTime", targetNamespace = "")
        java.lang.String localTime,
        @WebParam(name = "additionalData", targetNamespace = "")
        java.lang.String additionalData,
        @WebParam(name = "callBackUrl", targetNamespace = "")
        java.lang.String callBackUrl,
        @WebParam(name = "payerId", targetNamespace = "")
        java.lang.String payerId,
        @WebParam(name = "subServiceId", targetNamespace = "")
        long subServiceId,
        @WebParam(name = "mobileNo", targetNamespace = "")
        java.lang.String mobileNo,
        @WebParam(name = "encPan", targetNamespace = "")
        java.lang.String encPan,
        @WebParam(name = "panHiddenMode", targetNamespace = "")
        java.lang.String panHiddenMode,
        @WebParam(name = "cartItem", targetNamespace = "")
        java.lang.String cartItem,
        @WebParam(name = "enc", targetNamespace = "")
        java.lang.String enc
    );

    @WebMethod
    @RequestWrapper(localName = "bpInquiryRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpInquiryRequest")
    @ResponseWrapper(localName = "bpInquiryRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpInquiryRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpInquiryRequest(

        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "saleOrderId", targetNamespace = "")
        long saleOrderId,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        long saleReferenceId
    );

    @WebMethod
    @RequestWrapper(localName = "bpSettleRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpSettleRequest")
    @ResponseWrapper(localName = "bpSettleRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpSettleRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpSettleRequest(

        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "saleOrderId", targetNamespace = "")
        long saleOrderId,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        long saleReferenceId
    );

    @WebMethod
    @RequestWrapper(localName = "bpVerifySettleRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpVerifySettleRequest")
    @ResponseWrapper(localName = "bpVerifySettleRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpVerifySettleRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpVerifySettleRequest(

        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "saleOrderId", targetNamespace = "")
        long saleOrderId,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        long saleReferenceId
    );

    @WebMethod
    @RequestWrapper(localName = "bpRefundRequestV2", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpRefundRequestV2")
    @ResponseWrapper(localName = "bpRefundRequestV2Response", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpRefundRequestV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpRefundRequestV2(

        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "destinationPan", targetNamespace = "")
        java.lang.String destinationPan,
        @WebParam(name = "mobileNo", targetNamespace = "")
        java.lang.String mobileNo,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "saleOrderId", targetNamespace = "")
        long saleOrderId,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        long saleReferenceId,
        @WebParam(name = "refundAmount", targetNamespace = "")
        long refundAmount
    );

    @WebMethod
    @RequestWrapper(localName = "soh", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.Soh")
    @ResponseWrapper(localName = "sohResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.SohResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean soh()
;

    @WebMethod
    @RequestWrapper(localName = "bpChargePayRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpChargePayRequest")
    @ResponseWrapper(localName = "bpChargePayRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpChargePayRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpChargePayRequest(

        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "amount", targetNamespace = "")
        long amount,
        @WebParam(name = "localDate", targetNamespace = "")
        java.lang.String localDate,
        @WebParam(name = "localTime", targetNamespace = "")
        java.lang.String localTime,
        @WebParam(name = "additionalData", targetNamespace = "")
        java.lang.String additionalData,
        @WebParam(name = "callBackUrl", targetNamespace = "")
        java.lang.String callBackUrl,
        @WebParam(name = "payerId", targetNamespace = "")
        java.lang.String payerId
    );

    @WebMethod
    @RequestWrapper(localName = "bpCumulativeDynamicPayRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpCumulativeDynamicPayRequest")
    @ResponseWrapper(localName = "bpCumulativeDynamicPayRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpCumulativeDynamicPayRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpCumulativeDynamicPayRequest(

        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "amount", targetNamespace = "")
        long amount,
        @WebParam(name = "localDate", targetNamespace = "")
        java.lang.String localDate,
        @WebParam(name = "localTime", targetNamespace = "")
        java.lang.String localTime,
        @WebParam(name = "additionalData", targetNamespace = "")
        java.lang.String additionalData,
        @WebParam(name = "callBackUrl", targetNamespace = "")
        java.lang.String callBackUrl,
        @WebParam(name = "mobileNo", targetNamespace = "")
        java.lang.String mobileNo,
        @WebParam(name = "encPan", targetNamespace = "")
        java.lang.String encPan,
        @WebParam(name = "panHiddenMode", targetNamespace = "")
        java.lang.String panHiddenMode,
        @WebParam(name = "cartItem", targetNamespace = "")
        java.lang.String cartItem,
        @WebParam(name = "enc", targetNamespace = "")
        java.lang.String enc
    );

    @WebMethod
    @RequestWrapper(localName = "bpPayRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpPayRequest")
    @ResponseWrapper(localName = "bpPayRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpPayRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpPayRequest(

        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "amount", targetNamespace = "")
        long amount,
        @WebParam(name = "localDate", targetNamespace = "")
        java.lang.String localDate,
        @WebParam(name = "localTime", targetNamespace = "")
        java.lang.String localTime,
        @WebParam(name = "additionalData", targetNamespace = "")
        java.lang.String additionalData,
        @WebParam(name = "callBackUrl", targetNamespace = "")
        java.lang.String callBackUrl,
        @WebParam(name = "payerId", targetNamespace = "")
        java.lang.String payerId,
        @WebParam(name = "mobileNo", targetNamespace = "")
        java.lang.String mobileNo,
        @WebParam(name = "encPan", targetNamespace = "")
        java.lang.String encPan,
        @WebParam(name = "panHiddenMode", targetNamespace = "")
        java.lang.String panHiddenMode,
        @WebParam(name = "cartItem", targetNamespace = "")
        java.lang.String cartItem,
        @WebParam(name = "enc", targetNamespace = "")
        java.lang.String enc
    );

    @WebMethod
    @RequestWrapper(localName = "bpRefundInquiryRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpRefundInquiryRequest")
    @ResponseWrapper(localName = "bpRefundInquiryRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpRefundInquiryRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpRefundInquiryRequest(

        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "refundOrderId", targetNamespace = "")
        long refundOrderId,
        @WebParam(name = "refundReferenceId", targetNamespace = "")
        long refundReferenceId
    );

    @WebMethod
    @RequestWrapper(localName = "bpReversalRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpReversalRequest")
    @ResponseWrapper(localName = "bpReversalRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpReversalRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpReversalRequest(

        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "saleOrderId", targetNamespace = "")
        long saleOrderId,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        long saleReferenceId
    );

    @WebMethod
    @RequestWrapper(localName = "bpPosRefundRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpPosRefundRequest")
    @ResponseWrapper(localName = "bpPosRefundRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpPosRefundRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpPosRefundRequest(

        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        long saleReferenceId,
        @WebParam(name = "refundAmount", targetNamespace = "")
        long refundAmount
    );

    @WebMethod
    @RequestWrapper(localName = "bpRefundToPANRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpRefundToPANRequest")
    @ResponseWrapper(localName = "bpRefundToPANRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpRefundToPANRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpRefundToPANRequest(

        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "pan", targetNamespace = "")
        java.lang.Long pan,
        @WebParam(name = "amount", targetNamespace = "")
        long amount,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        java.lang.Long saleReferenceId,
        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "mobileNo", targetNamespace = "")
        java.lang.String mobileNo,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId
    );

    @WebMethod
    @RequestWrapper(localName = "bpVerifyRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpVerifyRequest")
    @ResponseWrapper(localName = "bpVerifyRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpVerifyRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpVerifyRequest(

        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "saleOrderId", targetNamespace = "")
        long saleOrderId,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        long saleReferenceId
    );

    @WebMethod
    @RequestWrapper(localName = "bpRefundVerifyRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpRefundVerifyRequest")
    @ResponseWrapper(localName = "bpRefundVerifyRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "edu.imi.ir.eduimiws.models.wsdl.BpRefundVerifyRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bpRefundVerifyRequest(

        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        java.lang.String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "refundOrderId", targetNamespace = "")
        long refundOrderId,
        @WebParam(name = "refundReferenceId", targetNamespace = "")
        long refundReferenceId
    );
}
