package edu.imi.ir.eduimiws.mapper.crm;

import edu.imi.ir.eduimiws.domain.crm.ContactEntity;
import edu.imi.ir.eduimiws.mapper.CycleAvoidingMappingContext;
import edu.imi.ir.eduimiws.models.dto.crm.ContactDto;
import edu.imi.ir.eduimiws.utilities.PersistenceUtils;
import org.mapstruct.*;

import java.util.List;


@Mapper(componentModel = "spring",
        uses = {AccountMapper.class},
        imports = {PersistenceUtils.class},
        unmappedTargetPolicy = org.mapstruct.ReportingPolicy.IGNORE,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        nullValueMappingStrategy = NullValueMappingStrategy.RETURN_NULL,
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)
public interface ContactMapper {


    @Named("toContactEntity")
    @Mappings({
            @Mapping(source = "id", target = "id"),
            @Mapping(source = "account", target = "account", qualifiedByName = "toAccountEntity"),
//            omiddo: refactor later
//            @Mapping(source = "accountId", target = "account.id"),
            @Mapping(source = "salutation", target = "salutation"),
//            @Mapping(source = "salutationId", target = "salutation.id"),
            @Mapping(source = "firstName", target = "firstName"),
            @Mapping(source = "middleName", target = "middleName"),
            @Mapping(source = "lastName", target = "lastName"),
            @Mapping(source = "jobTitle", target = "jobTitle"),
            @Mapping(source = "businessPhone", target = "businessPhone"),
            @Mapping(source = "homePhone", target = "homePhone"),
            @Mapping(source = "mobilePhone", target = "mobilePhone"),
            @Mapping(source = "faxNumber", target = "faxNumber"),
            @Mapping(source = "pagerNumber", target = "pagerNumber"),
            @Mapping(source = "email", target = "email"),
            @Mapping(source = "currency", target = "currency"),
//            @Mapping(source = "currencyId", target = "currency.id"),
            @Mapping(source = "department", target = "department"),
            @Mapping(source = "role", target = "role"),
            @Mapping(source = "manager", target = "manager"),
//            @Mapping(source = "managerId", target = "manager.id"),
            @Mapping(source = "managerPhone", target = "managerPhone"),
            @Mapping(source = "assistant", target = "assistant"),
//            @Mapping(source = "assistantId", target = "assistant.id"),
            @Mapping(source = "assistantPhone", target = "assistantPhone"),
            @Mapping(source = "gender", target = "gender"),
            @Mapping(source = "maritalStatus", target = "maritalStatus"),
            @Mapping(source = "partnerName", target = "partnerName"),
            @Mapping(source = "birthdate", target = "birthdate"),
            @Mapping(source = "anniversary", target = "anniversary"),
            @Mapping(source = "description", target = "description"),
            @Mapping(source = "parent", target = "parent"),
//            @Mapping(source = "parentId", target = "parent.id"),
            @Mapping(source = "country", target = "country"),
//            @Mapping(source = "countryId", target = "country.id"),
            @Mapping(source = "state", target = "state"),
//            @Mapping(source = "stateId", target = "state.id"),
            @Mapping(source = "city", target = "city"),
//            @Mapping(source = "cityId", target = "city.id"),
            @Mapping(source = "addressPhone", target = "addressPhone"),
            @Mapping(source = "address", target = "address"),
            @Mapping(source = "company", target = "company"),
//            @Mapping(source = "companyId", target = "company.id"),
            @Mapping(source = "organization", target = "organization"),
//            @Mapping(source = "organizationId", target = "organization.id"),
            @Mapping(source = "leadSourceId", target = "leadSourceId"),
            @Mapping(source = "campaignId", target = "campaignId"),
            @Mapping(source = "teamId", target = "teamId"),
            @Mapping(source = "syncOutLook", target = "syncOutLook"),
            @Mapping(source = "preferredContactMethod", target = "preferredContactMethod"),
            @Mapping(source = "allowEmail", target = "allowEmail"),
            @Mapping(source = "allowBulkEmail", target = "allowBulkEmail"),
            @Mapping(source = "allowPhone", target = "allowPhone"),
            @Mapping(source = "allowFax", target = "allowFax"),
            @Mapping(source = "allowMail", target = "allowMail"),
            @Mapping(source = "addressType", target = "addressType"),
//            @Mapping(source = "addressTypeId", target = "addressType.id"),
            @Mapping(source = "userCreator", target = "userCreator"),
//            @Mapping(source = "userCreatorId", target = "userCreator.id"),
            @Mapping(source = "fromCity", target = "fromCity"),
            @Mapping(source = "certificateNo", target = "certificateNo"),
            @Mapping(source = "nationCode", target = "nationCode"),
            @Mapping(source = "fatherName", target = "fatherName"),
            @Mapping(source = "birthCity", target = "birthCity"),
//            @Mapping(source = "birthCityId", target = "birthCity.id"),
            @Mapping(source = "accessType", target = "accessType"),
            @Mapping(source = "image", target = "image"),
            @Mapping(source = "lfirstName", target = "lfirstName"),
            @Mapping(source = "llastName", target = "llastName"),
            @Mapping(source = "religion", target = "religion"),
//            @Mapping(source = "religionId", target = "religion.id"),
            @Mapping(source = "militaryService", target = "militaryService"),
//            @Mapping(source = "militaryServiceId", target = "militaryService.id"),
            @Mapping(source = "eduLevel", target = "eduLevel"),
//            @Mapping(source = "eduLevelId", target = "eduLevel.id"),
            @Mapping(source = "fieldName", target = "fieldName"),
            @Mapping(source = "bankName", target = "bankName"),
            @Mapping(source = "branchName", target = "branchName"),
            @Mapping(source = "bankAccountNumber", target = "bankAccountNumber"),
            @Mapping(source = "bankAccoountType", target = "bankAccoountType"),
            @Mapping(source = "entranceDate", target = "entranceDate"),
            @Mapping(source = "contractType", target = "contractType"),
//            @Mapping(source = "contractTypeId", target = "contractType.id"),
            @Mapping(source = "university", target = "university"),
            @Mapping(source = "insuranceKind", target = "insuranceKind"),
//            @Mapping(source = "insuranceKindId", target = "insuranceKind.id"),
            @Mapping(source = "insuranceBox", target = "insuranceBox"),
//            @Mapping(source = "insuranceBoxId", target = "insuranceBox.id"),
            @Mapping(source = "gender1", target = "gender1"),
            @Mapping(source = "marital1", target = "marital1"),
            @Mapping(source = "military1", target = "military1"),
            @Mapping(source = "editTempRowFlag", target = "editTempRowFlag"),
            @Mapping(source = "createTempRowFlag", target = "createTempRowFlag"),
            @Mapping(source = "verified", target = "verified"),
            @Mapping(source = "postalCode", target = "postalCode"),
            @Mapping(source = "editDate", target = "editDate"),
            @Mapping(source = "createDate", target = "createDate"),
            @Mapping(source = "userEditor", target = "userEditor"),
            @Mapping(source = "convertDateWho", target = "convertDateWho"),
            @Mapping(source = "convertUniq", target = "convertUniq"),
            @Mapping(source = "lfatherName", target = "lfatherName"),
            @Mapping(source = "lfromCity", target = "lfromCity"),
            @Mapping(source = "lfromCityEntity", target = "lfromCityEntity"),
//            @Mapping(source = "lfromCityEntityId", target = "lfromCityEntity.id")
    })
    ContactEntity toContactEntity(ContactDto contactDto , @Context CycleAvoidingMappingContext context);

    @Named("toContactDto")
    @Mappings({
            @Mapping(source = "id", target = "id"),
            @Mapping(source = "account", target = "account", qualifiedByName = "toAccountDto"),
            @Mapping(source = "salutation", target = "salutation"),
            @Mapping(source = "firstName", target = "firstName"),
            @Mapping(source = "middleName", target = "middleName"),
            @Mapping(source = "lastName", target = "lastName"),
            @Mapping(source = "jobTitle", target = "jobTitle"),
            @Mapping(source = "businessPhone", target = "businessPhone"),
            @Mapping(source = "homePhone", target = "homePhone"),
            @Mapping(source = "mobilePhone", target = "mobilePhone"),
            @Mapping(source = "faxNumber", target = "faxNumber"),
            @Mapping(source = "pagerNumber", target = "pagerNumber"),
            @Mapping(source = "email", target = "email"),
            @Mapping(source = "currency", target = "currency"),
            @Mapping(source = "currency.id", target = "currencyId"),
            @Mapping(source = "department", target = "department"),
            @Mapping(source = "role", target = "role"),
            @Mapping(source = "manager", target = "manager"),
            @Mapping(source = "manager.id", target = "managerId"),
            @Mapping(source = "managerPhone", target = "managerPhone"),
            @Mapping(source = "assistant", target = "assistant"),
            @Mapping(source = "assistant.id", target = "assistantId"),
            @Mapping(source = "assistantPhone", target = "assistantPhone"),
            @Mapping(source = "gender", target = "gender"),
            @Mapping(source = "maritalStatus", target = "maritalStatus"),
            @Mapping(source = "partnerName", target = "partnerName"),
            @Mapping(source = "birthdate", target = "birthdate"),
            @Mapping(source = "anniversary", target = "anniversary"),
            @Mapping(source = "description", target = "description"),
            @Mapping(source = "parent", target = "parent"),
            @Mapping(source = "parent.id", target = "parentId"),
            @Mapping(source = "country", target = "country"),
            @Mapping(source = "country.id", target = "countryId"),
            @Mapping(source = "state", target = "state"),
            @Mapping(source = "state.id", target = "stateId"),
            @Mapping(source = "city", target = "city"),
            @Mapping(source = "city.id", target = "cityId"),
            @Mapping(source = "addressPhone", target = "addressPhone"),
            @Mapping(source = "address", target = "address"),
            @Mapping(source = "company", target = "company"),
            @Mapping(source = "company.id", target = "companyId"),
            @Mapping(source = "organization", target = "organization"),
            @Mapping(source = "organization.id", target = "organizationId"),
            @Mapping(source = "leadSourceId", target = "leadSourceId"),
            @Mapping(source = "campaignId", target = "campaignId"),
            @Mapping(source = "teamId", target = "teamId"),
            @Mapping(source = "syncOutLook", target = "syncOutLook"),
            @Mapping(source = "preferredContactMethod", target = "preferredContactMethod"),
            @Mapping(source = "allowEmail", target = "allowEmail"),
            @Mapping(source = "allowBulkEmail", target = "allowBulkEmail"),
            @Mapping(source = "allowPhone", target = "allowPhone"),
            @Mapping(source = "allowFax", target = "allowFax"),
            @Mapping(source = "allowMail", target = "allowMail"),
            @Mapping(source = "addressType", target = "addressType"),
            @Mapping(source = "addressType.id", target = "addressTypeId"),
            @Mapping(source = "userCreator", target = "userCreator"),
            @Mapping(source = "userCreator.id", target = "userCreatorId"),
            @Mapping(source = "fromCity", target = "fromCity"),
            @Mapping(source = "certificateNo", target = "certificateNo"),
            @Mapping(source = "nationCode", target = "nationCode"),
            @Mapping(source = "fatherName", target = "fatherName"),
            @Mapping(source = "birthCity", target = "birthCity"),
            @Mapping(source = "birthCity.id", target = "birthCityId"),
            @Mapping(source = "accessType", target = "accessType"),
            @Mapping(source = "image", target = "image"),
            @Mapping(source = "lfirstName", target = "lfirstName"),
            @Mapping(source = "llastName", target = "llastName"),
            @Mapping(source = "religion", target = "religion"),
            @Mapping(source = "religion.id", target = "religionId"),
            @Mapping(source = "militaryService", target = "militaryService"),
            @Mapping(source = "militaryService.id", target = "militaryServiceId"),
            @Mapping(source = "eduLevel", target = "eduLevel"),
            @Mapping(source = "eduLevel.id", target = "eduLevelId"),
            @Mapping(source = "fieldName", target = "fieldName"),
            @Mapping(source = "bankName", target = "bankName"),
            @Mapping(source = "branchName", target = "branchName"),
            @Mapping(source = "bankAccountNumber", target = "bankAccountNumber"),
            @Mapping(source = "bankAccoountType", target = "bankAccoountType"),
            @Mapping(source = "entranceDate", target = "entranceDate"),
            @Mapping(source = "contractType", target = "contractType"),
            @Mapping(source = "contractType.id", target = "contractTypeId"),
            @Mapping(source = "university", target = "university"),
            @Mapping(source = "insuranceKind", target = "insuranceKind"),
            @Mapping(source = "insuranceKind.id", target = "insuranceKindId"),
            @Mapping(source = "insuranceBox", target = "insuranceBox"),
            @Mapping(source = "insuranceBox.id", target = "insuranceBoxId"),
            @Mapping(source = "gender1", target = "gender1"),
            @Mapping(source = "marital1", target = "marital1"),
            @Mapping(source = "military1", target = "military1"),
            @Mapping(source = "editTempRowFlag", target = "editTempRowFlag"),
            @Mapping(source = "createTempRowFlag", target = "createTempRowFlag"),
            @Mapping(source = "verified", target = "verified"),
            @Mapping(source = "postalCode", target = "postalCode"),
            @Mapping(source = "editDate", target = "editDate"),
            @Mapping(source = "createDate", target = "createDate"),
            @Mapping(source = "userEditor", target = "userEditor"),
            @Mapping(source = "convertDateWho", target = "convertDateWho"),
            @Mapping(source = "convertUniq", target = "convertUniq"),
            @Mapping(source = "lfatherName", target = "lfatherName"),
            @Mapping(source = "lfromCity", target = "lfromCity"),
            @Mapping(source = "lfromCityEntity", target = "lfromCityEntity"),
    })
    ContactDto toContactDto(ContactEntity contactEntity, @Context CycleAvoidingMappingContext context);


    @IterableMapping(qualifiedByName = "toContactEntity")
    List<ContactEntity> toContactEntities(List<ContactDto> ContactDtos, @Context CycleAvoidingMappingContext context);

    @IterableMapping(qualifiedByName = "toContactDto")
    List<ContactDto> toContactDtos(List<ContactEntity> contactEntities, @Context CycleAvoidingMappingContext context);

    @BeforeMapping
    @InheritConfiguration(name = "toContactDto")
    default void handleContactApiPublicIds(ContactEntity contactEntity,
                                          @MappingTarget ContactDto contactDto) {
        new PersistenceUtils().cleanFromProxyByReadMethod(contactEntity);
    }
}
