package edu.imi.ir.eduimiws.mapper.crm;

import edu.imi.ir.eduimiws.domain.crm.OrganizationApiEntity;
import edu.imi.ir.eduimiws.mapper.CycleAvoidingMappingContext;
import edu.imi.ir.eduimiws.models.dto.crm.OrganizationApiDto;
import edu.imi.ir.eduimiws.utilities.PersistenceUtils;
import org.mapstruct.*;

import java.util.List;

@Mapper(componentModel = "spring",
        uses = {AccountMapper.class, OrganizationMapper.class},
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.SET_TO_NULL,
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)
public interface OrganizationApiMapper {


    @Named("toOrganizationApiDto")
    @Mappings({
            @Mapping(source = "id", target = "id"),
            @Mapping(source = "account", target = "account"),
            @Mapping(source = "account.id", target = "accountId"),
            @Mapping(source = "accountPublicId", target = "accountPublicId"),
            @Mapping(source = "deletedOrganizationId", target = "deletedOrganizationId"),
            @Mapping(source = "deletedDateTs", target = "deletedDateTs"),
            @Mapping(source = "editDateTs", target = "editDateTs"),
            @Mapping(source = "organizationPublicId", target = "organizationPublicId"),
            @Mapping(source = "organization", target = "organization"),
            @Mapping(source = "organization.id", target = "organizationId")
    })
    @BeanMapping(ignoreByDefault = true)
    OrganizationApiDto toOrganizationApiDto(OrganizationApiEntity organizationApiEntity
            , @Context CycleAvoidingMappingContext context);

//    organizationApiEntity generated by Trigger

    @IterableMapping(qualifiedByName = "toOrganizationApiDto")
    List<OrganizationApiDto> toOrganizationApiDtos(List<OrganizationApiEntity> organizationApiEntities, @Context CycleAvoidingMappingContext context);

    @BeforeMapping
    default void handleLazyInitialization(OrganizationApiEntity organizationApi, @MappingTarget OrganizationApiDto organizationApiDto) {
        new PersistenceUtils().cleanFromProxyByReadMethod(organizationApi);
    }

}
